= Context
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== Ajuntament de Barcelona

El *Pla Barcelona Ciutat Digital* (PBCD), aprovat el passat mes d'octubre de 2016, és un Pla transversal que vol assegurar una política tecnològica coherent i homogènia dins l'Ajuntament en els eixos de Govern i Ciutat, Empreses i Entitats Socials i Ciutadania.

El PBCD ha d'assegurar que la tecnologia i la innovació digital actuen de facilitadors en la consecució d'unes polítiques públiques equitatives i eficients orientades a cobrir millor les necessitats dels ciutadans i ciutadanes i potenciar les seves capacitats, per a conformar uns serveis públics de major qualitat, amb l'òptima assignació i utilització dels recursos i el talent públic.

Dins del PBCD s'han definit tres eixos estratègics amb els següents objectius (Figura 1):

image::open-digit-p9-axes-{lang}.svg[FIGURA 1]

El Pla de Transformació Digital de l'Ajuntament de Barcelona (PTDA) és el full de ruta dels projectes TIC del mandat, global i per a cada Gerència, d'acord amb les prioritats polítiques.
Aquest pla inclou també els projectes d'actualització tecnològica i els projectes d'adequació al nou marc legal establert per la Llei 39/2015, d'1 d'octubre, de Procediment Administratiu Comú de les Administracions Públiques (LPCAP).

== Marc Legal

La Llei 39/2015, d'1 d'octubre, de Procediment Administratiu Comú de les Administracions Públiques (LPCAP) que impulsa l'administració digital d'una forma integral: tant la relació amb el ciutadà, com la gestió electrònica del procediment administratiu, el document i expedient electrònic, la interoperabilitat, etc. defineix un nou marc legal que obliga a canvis profunds en la prestació dels serveis públics i en conseqüència en l'organització municipal i els seus sistemes informàtics.

Cal indicar que a més del compliment de la LPACAP, en el context normatiu de la UE, la legislació espanyola i la catalana, trobem també altres textos legals als que també s'ha de donar resposta:

* El Pla d'Acció d'Administració Electrònica 2016-2020 de la UE, amb l'objectiu d'eliminar els obstacles digitals que s'oposen al Mercat Únic Digital i evitar la fragmentació que es pot generar en el context de transformació de les administracions públiques.

* El nou Reglament General de Protecció de Dades europeu (RGPD) aprovat el maig de 2016, al qual s'ha d'adaptar i complir tota administració pública.

* La Llei 19/2014, de 29 de desembre de transparència, accés a la informació pública i bon govern.
Aquesta llei té per objecte facilitar als ciutadans el coneixement de les actuacions de les administracions públiques autonòmiques, i el control i transparència en el destí dels diners públics.

* La Llei 39/2015, d'1 d'octubre, de règim jurídic del sector públic, que recull lo previst a la derogada Llei 11/2007 de 22 de juny, d'accés electrònic dels ciutadans a l'administració, (coneguda com LAESCP).
En aquest context, el programari lliure, els estàndards i les tecnologies de fonts obertes estan considerats com la millor opció per al desenvolupament d'un model tecnològic d'Administració a la mida de les necessitats i els objectius específics de l'Administració públic basat en criteris estratègics de transparència, control, seguretat, interoperabilitat, accés i conservació de la informació, economia, reutilització o cooperació entre organitzacions, contra els quals difícilment poden competir les tecnologies tancades.

* Reial Decret 4/2010 de 8 de gener, per el que es regula la l'Esquema Nacional d'Interoperabilitat, el qual compren els criteris i recomanacions de seguretat, normalització i conservació de la informació, dels formats i de les aplicacions que hauran de ser tinguts en compte per les Administracions públiques per assegurar un adequat nivell d'interoperabilitat organitzativa, semàntica i tècnica de les dades, informacions i serveis que gestionin en l'exercici de les seves competències i per evitar la discriminació als ciutadans per raó de la seva elecció tecnològica.

== Noves Tendències en el desenvolupament de serveis digitals àgils, sobirania tecnològica i de gestió ètica de dades

En la situació actual en què els canvis es produeixen de manera increïblement ràpida i es produeixen canvis dins dels canvis calen models de desenvolupament i implementació de serveis digitals que ens ajudin a adaptarnos a aquestes transformacions.
Aquesta afirmació és molt més encertada en el sector de les tecnologies de la informació i les comunicacions (TIC) en el qual la velocitat i agilitat davant del canvi és fonamental.
Per aquesta raó, i davant de les dificultats i a vegades fracassos experimentats amb les metodologies tradicionals de gestió de projectes, han sorgit les metodologies àgils.

Quan es parla de metodologies àgils, es fa referència a un grup de metodologies, d'acord amb el “manifest àgil”footnote:[_Manifest àgil - font http://agilemanifesto.org_] de 2001, aplicades en la creació i el desenvolupament de programari en iteracions, en el qual les necessitats i solucions evolucionen a través de la col·laboració entre els diferents equips involucrats en el projecte.

Les metodologies àgils promouen una gestió de projectes disciplinada que fomenta la constant revisió i adaptació a les necessitats dels usuaris i als canvis.Proporcionen un sistema organitzat que permet i facilita el treball en equip i l'autoorganització i afavoreixen la reducció del temps de desenvolupament.

En referència a la sobirania tecnològica i de dades, podem afirmar que el programari lliure i de codi obert és “_tècnicament viable, econòmicament sostenible i socialment just:_” footnote:[_Jordi Mas al seu llibre homònim (Col·lecció “Manuals i Formularis”, 15)_].
Això es reflexa en uns beneficis concrets en l'administració local.

* És *tècnicament viable* perquè permet reaprofitar projectes lliures existents, gràcies a la reducció de l'esforç d'implementació per cobrir necessitats pròpies.
Tota empresa informàtica, amb independència de la seva mida, depèn en major o menor grau de programari lliure.
Que l'Administració local en faci ús directament és un pas lògic.

La llibertat d'escollir eines també significa llibertat de proveïdor per al seu manteniment i desenvolupament.
Treballar amb formats i estàndards oberts permet no dependre d'una sola empresa o eina i tenir accés sempre a la informació generada.

Participar directament en la comunitat dóna accés a coneixements consolidats d'altres entitats, podent contribuir-hi amb documentació, codi o compartint experiències implementant el projecte a l'Administració.

* És *econòmicament sostenible* perquè elimina moltes despeses en llicències d'ús i retalla altres costos.
Aquesta reducció no vol dir una pèrdua de qualitat ni de seguretat.
Al contrari, pot fer viables projectes que amb programari privatiu no són possibles i mantenir els sistemes actualitzats i protegits al menor cost possible.

L'estalvi pot reinvertir-se en maquinari adient per a les noves eines o a partides que necessitin recursos addicionals.
Així, l'Administració mostra responsabilitat vers els diners públics i n'exerceix una gestió responsable.

Amb la llibertat d'escollir proveïdor sense restriccions es pot potenciar la reinversió dels diners públics al territori tot afavorint l'economia de proximitat.
Generant un cercle virtuós on qualsevol pime, cooperativa i autònom pot oferir els seus serveis, en igualtat de condicions.
En un país on el 90% de les empreses són petites i mitjanes, això obre un ventall de possibilitats molt ampli.

També permet escollir la gestió municipal de la infraestructura informàtica, sense necessitar especialitzacions en eines privatives a alts costos.
L'oferta laboral generada, pública o privada, serà accessible a més professionals del territori.

* És *socialment just* perquè garanteix els drets fonamentals de la ciutadania.
L'accés al codi font i el seu control col·lectiu ajuda a saber què fa i auditar que no tingui cap porta del darrera o vulnerabilitats de seguretat.
La privacitat i	seguretat de les dades resten assegurades.

Amb el programari privatiu, aquests beneficis no existeixen o exigeixen costos econòmics i socials superiors.

Des de l'any 2010, el Reial Decret 4/2010 (apartat 04.2) obliga a les Administracions Púbiques a utilitzar estàndards i formats oberts a l'hora de implementar serveis digitals i interactuar amb els ciutadans.
La llista d'estàndards i formats no és una elecció de cada entitat pública, sinó que existeix un llistat d'estàndards tipificat i normalitzat per la seva interoperabilitat.
Per tant, les Administracions públiques utilitzaran estàndards oberts a fi de garantir la independència en l'elecció d'alternatives tecnològiques, la preservació de documents en el temps, i l'adaptabilitat al progrés de la tecnologia.

Els documents, serveis electrònics i aplicacions posats per les Administracions públiques a la disposició dels ciutadans o d'altres Administracions públiques seran, segons correspongui, visualitzables, accessibles i funcionalment operables en condicions que permetin satisfer el principi de neutralitat tecnològica i evitin la discriminació als ciutadans per raó de la seva elecció tecnològica.

Fins fa poc temps les dades tenien una consideració residual i limitada, però la capacitat de procés informàtic ens ha portat a poder aprofitar i reutilitzar les dades.
Al mateix temps, aquestes dades han augmentat de forma exponencial.
Aquesta situació fa indispensable, per motius de seguretat, un control de les mateixes i a l'hora un alliberament per potenciar la seva reutilització, amb el convenciment que les dades publiques poden generar negoci i millora social per tota la població.
La combinació d'eines lliures i dades obertes ens situa a un nou horitzó on la transparència i la voluntat de compartir i treballar de forma comunitària, genera una nova organització de l'administració publica.

== Metodologies àgils i programari lliure a altres administracions públiques

*Metodologies àgils*

Si be és a l'empresa privada, i en particular a les Pimes, on s'han introduït i desplegat les metodologies àgils, les administracions publiques no son alienes a aquesta tendència.
Des de el 2012, el govern britànic ho promou footnote:[https://www.gov.uk/service-manual/agile-delivery], així com el Departament de Defensa dels Estats Units.
Un bon exemple és el desenvolupament del nous servei de gestió de les inspeccions automotors britàniques.

En l'entorn més proper, la Junta d'Andalusia al 2010 va licitar el servei pel desenvolupament del web “DESARROLLO DE LA WEB DE CONSUMO RESPONDE” mitjançant metodologia àgil SCRUM, segurament la més popular de les metodologies àgils de desenvolupament de software.
També al 2010 el govern de Canàries va licitar el servei de manteniment del sistema informàtic d'expedients en l'àmbit turístic mitjançant aquesta metodologia.

Al 2013, l'Ajuntament de Vitòria Gasteiz va licitar “la contractació de redisseny del web municipal fent servir disseny adaptatiu”, especificant la metodologia SCRUM en els plecs de prescripcions tècniques.

Al març de 2017, la Diputació de Badajoz va iniciar el procediment per a la contractació dels serveis de desenvolupament i implantació de noves funcionalitats, i l'evolució tecnològica dels seus actuals aplicatius de gestió utilitzant metodologia àgil SCRUM.

Institucions publico-privades com el Museu Thyssen, l'Hospital Clínic de Sant Carlos a Madrid i la seva _Smart Health Lab_ i fins i tot l'Agència Tributària estan començant a usar i aplicar tècniques àgils com _Lean Government_.

Barcelona va començar a introduir al 2013 les metodologies àgils per al desenvolupament i gestió dels webs municipals i ara serà la primera gran ciutat del sud d'Europa en posar en marxa i implementar aquest tipus de metodologies globalment dins de l'Ajuntament.

*Tecnologies obertes*

Pel que fa referència a experiències en tecnologies obertes, fa temps que les administracions públiques han iniciat el procés d'implementació de polítiques de tecnologies obertes i desplegaments de serveis basats en programari lliure i de codi obert.
A nivell regional, la Universitat de Lleida (UDL), és la universitat pública pionera en l'ús de programari lliure a Catalunya (juntament amb la Universitat Oberta de Catalunya).
Durant anys han utilitzat sistemes lliures amb resultats excel·lents, des de el 2003 quan va accedir al rectorat de l'UDL un nou equip que tenia com a un dels seus objectius, potenciar l'ús de programari lliure, i va iniciar un procés de migració de tots els sistemes.
Al 2006, la Generalitat de Catalunya publica el seu full de ruta de programari lliure.

La Universitat de Múrcia al 2014, es va adscriure al projecte Open Academic Environment (OAE), una iniciativa internacional per a la creació d'una plataforma de programari lliure, que permet desenvolupar una xarxa acadèmica col·laborativa de caràcter obert.
Aquest projecte està liderat per la Universitat de Cambridge, i la Universitat de Múrcia ha estat la primera universitat espanyola a participar.
Al 2015, va iniciar la migració dels seus equips a Linux.
Això els va a suposar un estalvi de 100.000 € en llicències i d'altres 300.000 € en evitar haver de renovar equips.
Recentment, Barcelona va publicar el codi de Sentilo, plataforma de gestió de dades per a sensors de la ciutat, com a programari lliure i va guanyar un premi europeu de reutilització (“_Sharing and Reuse Awards_”).

A nivell europeu, el Ministeri d'Exteriors alemany, al 2003, va iniciar la migració dels seus 11.000 ordinadors a GNU/Linux i a aplicacions de programari lliure.
Això ha permès reduir considerablement els costos si els comparem amb altres ministeris.
Es pretén que la migració es dugui a terme a les 230 ambaixades i consolats repartits arreu del món.
L'equip de TI de la Gendarmerie Nationale francesa, per tal de poder oferir un servei responsable i rendible a nivell nacional i per tal de reduir els creixents costos d'infraestructura de TI, va decidir a l'any 2004, revisar el seu entorn basat en Microsoft existent.
Es va migrar a OpenOffice, Firefox i es va fer una actualització de PC's cap a Ubuntu.
Això va provocar un estalvi de 2 milions d'euros anuals només en drets de llicència, també s'ha produït una reducció dràstica de les despeses en maquinari.

Italia, al 2014, va escollir el software lliure com la primera opció per a l'Administració Pública.
Van crear un document titulat “_Guias para la evaluación comparativa (de software)_”, on s'aprèn un mètode a seguir per prendre la decisió correcta a l'hora d'escollir un programari.
El cas italià és molt important perquè es preocupa no només per la norma, sinó per la seva implementació.
La guia elaborada per l'Agència Digital Italiana es va redactar amb participació tant de la Free Software Foundation Europe, com dels representants de diferents empreses de programari privatiu.

Les polítiques de tecnologies obertes per a l'administració pública europea son recolzades per l'acció de la Comissió Europea, que publica a la seva pròpia llicència lliure per a Administracions Públiques, la llicència EUPL, i centralitza els esforços en la seva plataforma “_Join Up_” on trobem literalment centenars d'experiències de migració o desenvolupament de programari lliure a les administracions europees.

A nivell internacional, al Brasil, el govern va iniciar en paral·lel diversos projectes d'inclusió digital en diferents zones, basats en l'establiment de telecentres, l'objectiu dels quals era reduir l'exclusió digital, augmentar la capacitat professional, difondre el programari lliure i augmentar la participació popular en les noves tecnologies.
El programari lliure ha jugat un paper fonamental en la creació d'aquests centres i està permetent que els qui acaben d'arribar al món digital puguin fer-ho amb programari legal.

Al 2004, el govern de Malàisia va iniciar el Pla mestre per a fomentar, adoptar i desenvolupar l'ús del programari lliure al sector públic, posant en marxa l'_Open Source Competency Center_ (OSCC) que va establir-se com un centre de referència nacional per a dirigir i donar suport a l'aplicació del programari lliure a l'Administració.

Més recentment, al 2013, la Índia va invertir en ordinador amb programari lliure (Ubuntu) per als seus estudiants.
És un dels programes més importants del món per a portàtils patrocinats pel govern, es porta a terme amb 1,5 milions d'ordinadors portàtils.

Respecte als formats i dades obertes, el 23 de juny del 2006, el Consell de Ministres de Bèlgica a Brussel·les va aprovar la decisió de requerir que tots els intercanvis documentals en els serveis del Govern Federal Belga es produeixin en formats oberts i estàndards.
Per tant, i expressament, només OpenDocument (ODF) va estar acceptat com a tal estàndard en aquesta decisió.

Al 2010 va néixer el projecte Open Data BCN, implantant el portal a l'any 2011, que té com a principal objectiu aprofitar al màxim els recursos públics disponibles, exposant la informació generada o custodiada per organismes públics, permetent el seu accés i reutilització per al bé comú i per al benefici de persones i entitats interessades.
El projecte que s'emmarca dins de l'estratègia Barcelona Ciutat Digital, es basa en els principals estàndards i recomanacions internacionals, adoptant les característiques, de dades obertes per defecte, qualitat i quantitat d'informació, dades per a tothom, dades per a la millora de la governança i promoció a la innovació.

Tal i com hem pogut veure en els casos que s'han descrit, des de fa molts anys les administracions estan desplegant un procés de transformació cap a metodologies àgils i programari lliure.
En algunes d'elles ja s'han pogut demostrar de forma clara els seus beneficis, tant a nivell d'estalvi econòmic i mitigació de la obsolescència tecnològica amb la incorporació de programari lliure, com en la millora de la productivitat i adaptació a través de les metodologies àgils.
