= Contexto
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== Ayuntamiento de Barcelona

El PBCD, aprobado el pasado mes de octubre del 2016, es un plan transversal con el que se pretende asegurar una política tecnológica coherente y homogénea dentro del Ayuntamiento en los ejes de gobierno y ciudad, empresas y entidades sociales y ciudadanía.

El PBCD debe asegurar que la tecnología y la innovación digital actúan de facilitadores en la consecución de unas políticas públicas equitativas y eficientes orientadas a cubrir mejor las necesidades de la ciudadanía y potenciar sus capacidades, para conformar unos servicios públicos de mayor calidad, con la óptima asignación y utilización de los recursos y el talento público.

Dentro del plan se han definido tres ejes estratégicos, con los siguientes objetivos (figura 1):

image::open-digit-p9-axes-{lang}.svg[FIGURA 1, align="center"]

El PTDA es la hoja de ruta de los proyectos TIC del mandato, global y para cada gerencia, de acuerdo con las prioridades políticas.
Este plan incluye también los proyectos de actualización tecnológica y los proyectos de adecuación al nuevo marco legal establecido por la Ley 39/2015, de 1 de octubre, de procedimiento administrativo común de las administraciones públicas.

== Marco Legal

La Ley 39/2015, de 1 de octubre, de procedimiento administrativo común de las administraciones públicas, que impulsa la Administración digital de una forma integral, tanto la relación con el ciudadano como la gestión electrónica del procedimiento administrativo, el documento y expediente electrónico, la interoperabilidad, etcétera, define un nuevo marco legal que obliga a hacer cambios profundos en la prestación de los servicios públicos y, en consecuencia, en la organización municipal y sus sistemas informáticos.

Hay que indicar que, además del cumplimiento de la mencionada ley, en el contexto normativo de la Unión Europea (UE), la legislación española y la catalana, encontramos también otros textos legales a los que también debe darse respuesta:

* El Plan de acción de Administración electrónica 2016-2020 de la UE, con el objetivo de eliminar los obstáculos digitales que se oponen al mercado único digital y evitar la fragmentación que se puede generar en el contexto de transformación de las administraciones públicas.

* El nuevo Reglamento general de protección de datos europeo, aprobado en mayo del 2016, al que se tiene que adaptar y que debe cumplir toda Administración pública.

* La Ley 19/2014, de 29 de diciembre, de transparencia, acceso a la información pública y buen gobierno.
Esta ley tiene por objeto facilitar a los ciudadanos el conocimiento de las actuaciones de las administraciones públicas autonómicas y el control y la transparencia en el destino del dinero público.

* La Ley 11/2007, de 22 de junio, de acceso electrónico de los ciudadanos a la Administración, conocida como LAESCP.
En este contexto, el software libre, los estándares y las tecnologías de fuentes abiertas están considerados la mejor opción para el desarrollo de un modelo tecnológico de e-Administración a la medida de las necesidades y los objetivos específicos de la Administración pública, basado en criterios estratégicos de transparencia, control, seguridad, interoperabilidad, acceso y conservación de la información, economía, reutilización o cooperación entre organizaciones, contra los que difícilmente pueden competir las tecnologías cerradas.

* Real decreto 4/2010, de 8 de enero, por el que se regula el Esquema Nacional de Interoperabilidad, que comprende los criterios y recomendaciones de seguridad, normalización y conservación de la información, de los formatos y de las aplicaciones que deberán tener en cuenta las administraciones públicas para asegurar un adecuado nivel de interoperabilidad organizativa, semántica y técnica de los datos, las informaciones y los servicios que gestionen en el ejercicio de sus competencias y para evitar la discriminación a la ciudadanía por su elección tecnológica.
Informaciones y servicios que gestionen en el ejercicio de sus competencias y para evitar la discriminación a los ciudadanos pera razón de su elección tecnológica.

== Nuevas tendencias en el desarrollo de servicios digitales ágiles, soberanía tecnológica y gestión ética de datos

En la situación actual, en que los cambios se producen de manera increíblemente rápida y en que se producen cambios dentro de los cambios, se necesitan modelos de desarrollo e implementación de servicios digitales que nos ayuden a adaptarnos a estas transformaciones.
Esta afirmación es mucho más acertada en el sector de las TIC, en el que la velocidad y la agilidad ante el cambio son fundamentales.
Por esta razón, y ante las dificultades y a veces fracasos experimentados con las metodologías tradicionales de gestión de proyectos, han surgido las metodologías ágiles.

Cuando se habla de metodologías ágiles, se hace referencia a un grupo de metodologías, de acuerdo con el “Manifiesto Agile”footnote:[_Manifesto ágil - font http://agilemanifesto.org_] del 2001, aplicadas en la creación de software que basa su desarrollo en un ciclo iterativo, en el que las necesidades y soluciones evolucionan mediante la colaboración entre los diferentes equipos involucrados en el proyecto.

Las metodologías ágiles promueven una gestión de proyectos disciplinada que fomenta la constante revisión y adaptación a las necesidades de los usuarios y a los cambios.
Proporcionan un sistema organizado que permite y facilita el trabajo en equipo y la autoorganización y favorecen la reducción del tiempo de desarrollo.

En referencia a la soberanía tecnológica y de datos, podemos afirmar que el software libre es “_técnicamente viable, económicamente sostenible y socialmente justo_” footnote:[_Jordi Mas, en su libro homónimo (Colección “Manuales y Formularios”, 15)._].
Eso se refleja en unos beneficios concretos en la Administración local.
////
A continuación se detallan estas tres características:
////

* Es *técnicamente viable* porque permite reaprovechar proyectos libres existentes, gracias a la reducción del esfuerzo de implementación para cubrir necesidades propias.
Toda empresa informática, con independencia de su tamaño, depende en mayor o menor grado de software libre.
Que la Administración local haga uso de él directamente es un paso lógico.

La libertad de escoger herramientas también significa libertad de proveedor para su mantenimiento y desarrollo.
Trabajar con formatos y estándares abiertos permite no depender de una gran empresa y tener acceso siempre a la información generada.

Participar directamente en la comuni-dad da acceso a conocimientos consolidados de otras entidades, y se puede contribuir con documentación o código o compartir experiencias implementando el proyecto en la Administración.

* Es *económicamente sostenible* porque elimina posibles licencias de uso y reduce costes.
Esta reducción no significa una pérdida de calidad ni de seguridad.
Al contrario, puede hacer viables proyectos que con software privativo no son posibles y mantener los sistemas actualizados y protegidos al menor coste posible.

El ahorro puede reinvertirse en _hardware_ adecuado para las nuevas herramientas o en partidas que necesiten recursos adicionales.
Así, la Administración local muestra responsabilidad hacia el dinero público y ejerce una gestión responsable.

Con la libertad de escoger proveedor sin restricciones se puede potenciar la reinversión del dinero público en el territorio, lo que favorece la economía de proximidad y genera un círculo virtuoso donde cualquier pyme, cooperativa y autónomo puede ofrecer sus servicios, en igualdad de condiciones.
En un país donde el 90 % de las empresas son pequeñas y medianas, eso abre un abanico de posibilidades muy amplio.

También permite escoger la gestión municipal de la infraestructura informática, sin necesitar especializaciones en herramientas privativas a altos costes.
La oferta laboral generada, pública o privada, será accesible a más profesionales del territorio.

* Es *socialmente justo* porque garantiza los derechos fundamentales de la ciudadanía.
El acceso al código fuente y su control colectivo ayuda a saber qué hace y a auditar que no tenga ninguna brecha o vulnerabilidad en cuanto a seguridad.
La privacidad y la seguridad de los datos quedan aseguradas.

Con el _software_ privativo, estos beneficios no existen o exigen costes económicos y sociales superiores

////
*Tendencias en estándares abiertos (e.g European in Teroperability Framework, o Rd 4/2010)*
////

Desde el año 2010, existe el Real decreto 4/2010 (apartado 04.2), que obliga a las administraciones públicas a utilizar formatos abiertos a la hora de compartir información con la ciudadanía.
La lista de formatos no es una elección de cada entidad pública, sino que existe un listado de estándares tipificado y normalizado por su interoperabilidad.
Por lo tanto, las administraciones públicas utilizarán estándares abiertos con el fin de garantizar la independencia en la elección de alternativas tecnológicas para la ciudadanía y las administraciones públicas y la adaptabilidad al progreso de la tecnología.

Los documentos, servicios electrónicos y aplicaciones que las administraciones públicas han puesto a disposición de la ciudadanía o de otras administraciones públicas serán, según corresponda, visualizables, accesibles y funcionalmente operables, en condiciones que permitan satisfacer el principio de neutralidad tecnológica y que eviten la discriminación a la ciudadanía en razón de su elección tecnológica.

////
*Tendencias en gestión ética de datos*
////

Hasta hace poco tiempo los datos tenían una consideración residual y limitada, pero la capacidad de proceso informático nos ha llevado a poder aprovechar y reutilizar los datos.
Al mismo tiempo, estos datos han aumentado de manera exponencial.
Esta situación hace indispensable, por motivos de seguridad, un control de los datos y a la vez una liberación para potenciar su reutilización, con el convencimiento de que los datos públicos pueden generar negocio y mejora social para toda la población.
La combinación de herramientas libres y datos abiertos nos sitúa en un nuevo horizonte en el que la transparencia y la voluntad de compartir y trabajar de forma comunitaria generan una nueva organización de la Administración pública.

== Metodologías ágiles y software libre en otras administraciones públicas

////
*Metodologías ágiles*
////

Si be és a l'empresa privada, i en particular a les Pimes, on s'han introduït i desplegat les metodologies àgils, les administracions publiques no son alienes a aquesta tendència.
Des de el 2012, el govern britànic ho promou footnote:[https://www.gov.uk/service-manual/agile-delivery], així com el Departament de Defensa dels Estats Units.
Un bon exemple és el desenvolupament del nous servei de gestió de les inspeccions automotors britàniques.

En l'entorn més proper, la Junta d'Andalusia al 2010 va licitar el servei pel desenvolupament del web “DESARROLLO DE LA WEB DE CONSUMO RESPONDE” mitjançant metodologia àgil SCRUM, segurament la més popular de les metodologies àgils de desenvolupament de software.
També al 2010 el govern de Canàries va licitar el servei de manteniment del sistema informàtic d'expedients en l'àmbit turístic mitjançant aquesta metodologia.

Al 2013, l'Ajuntament de Vitòria Gasteiz va licitar “la contractació de redisseny del web municipal fent servir disseny adaptatiu”, especificant la metodologia SCRUM en els plecs de prescripcions tècniques.

Al març de 2017, la Diputació de Badajoz va iniciar el procediment per a la contractació dels serveis de desenvolupament i implantació de noves funcionalitats, i l'evolució tecnològica dels seus actuals aplicatius de gestió utilitzant metodologia àgil SCRUM.

Institucions publico-privades com el Museu Thyssen, l'Hospital Clínic de Sant Carlos a Madrid i la seva _Smart Health Lab_ i fins i tot l'Agència Tributària estan començant a usar i aplicar tècniques àgils com _Lean Government_.

Barcelona va començar a introduir al 2013 les metodologies àgils per al desenvolupament i gestió dels webs municipals i ara serà la primera gran ciutat del sud d'Europa en posar en marxa i implementar aquest tipus de metodologies globalment dins de l'Ajuntament.

*Tecnologies obertes*

Pel que fa referència a experiències en tecnologies obertes, fa temps que les administracions públiques han iniciat el procés d'implementació de polítiques de tecnologies obertes i desplegaments de serveis basats en programari lliure i de codi obert.
A nivell regional, la Universitat de Lleida (UDL), és la universitat pública pionera en l'ús de programari lliure a Catalunya (juntament amb la Universitat Oberta de Catalunya).
Durant anys han utilitzat sistemes lliures amb resultats excel·lents, des de el 2003 quan va accedir al rectorat de l'UDL un nou equip que tenia com a un dels seus objectius, potenciar l'ús de programari lliure, i va iniciar un procés de migració de tots els sistemes.
Al 2006, la Generalitat de Catalunya publica el seu full de ruta de programari lliure.

La Universitat de Múrcia al 2014, es va adscriure al projecte Open Academic Environment (OAE), una iniciativa internacional per a la creació d'una plataforma de programari lliure, que permet desenvolupar una xarxa acadèmica col·laborativa de caràcter obert.
Aquest projecte està liderat per la Universitat de Cambridge, i la Universitat de Múrcia ha estat la primera universitat espanyola a participar.
Al 2015, va iniciar la migració dels seus equips a Linux.
Això els va a suposar un estalvi de 100.000 € en llicències i d'altres 300.000 € en evitar haver de renovar equips.
Recentment, Barcelona va publicar el codi de Sentilo, plataforma de gestió de dades per a sensors de la ciutat, com a programari lliure i va guanyar un premi europeu de reutilització (“_Sharing and Reuse Awards_”).

A nivell europeu, el Ministeri d'Exteriors alemany, al 2003, va iniciar la migració dels seus 11.000 ordinadors a GNU/Linux i a aplicacions de programari lliure.
Això ha permès reduir considerablement els costos si els comparem amb altres ministeris.
Es pretén que la migració es dugui a terme a les 230 ambaixades i consolats repartits arreu del món.
L'equip de TI de la Gendarmerie Nationale francesa, per tal de poder oferir un servei responsable i rendible a nivell nacional i per tal de reduir els creixents costos d'infraestructura de TI, va decidir a l'any 2004, revisar el seu entorn basat en Microsoft existent.
Es va migrar a OpenOffice, Firefox i es va fer una actualització de PC's cap a Ubuntu.
Això va provocar un estalvi de 2 milions d'euros anuals només en drets de llicència, també s'ha produït una reducció dràstica de les despeses en maquinari.

Italia, al 2014, va escollir el software lliure com la primera opció per a l'Administració Pública.
Van crear un document titulat “_Guias para la evaluación comparativa (de software)_”, on s'aprèn un mètode a seguir per prendre la decisió correcta a l'hora d'escollir un programari.
El cas italià és molt important perquè es preocupa no només per la norma, sinó per la seva implementació.
La guia elaborada per l'Agència Digital Italiana es va redactar amb participació tant de la Free Software Foundation Europe, com dels representants de diferents empreses de programari privatiu.

Les polítiques de tecnologies obertes per a l'administració pública europea son recolzades per l'acció de la Comissió Europea, que publica a la seva pròpia llicència lliure per a Administracions Públiques, la llicència EUPL, i centralitza els esforços en la seva plataforma “_Join Up_” on trobem literalment centenars d'experiències de migració o desenvolupament de programari lliure a les administracions europees.

A nivell internacional, al Brasil, el govern va iniciar en paral·lel diversos projectes d'inclusió digital en diferents zones, basats en l'establiment de telecentres, l'objectiu dels quals era reduir l'exclusió digital, augmentar la capacitat professional, difondre el programari lliure i augmentar la participació popular en les noves tecnologies.
El programari lliure ha jugat un paper fonamental en la creació d'aquests centres i està permetent que els qui acaben d'arribar al món digital puguin fer-ho amb programari legal.

Al 2004, el govern de Malàisia va iniciar el Pla mestre per a fomentar, adoptar i desenvolupar l'ús del programari lliure al sector públic, posant en marxa l'_Open Source Competency Center_ (OSCC) que va establir-se com un centre de referència nacional per a dirigir i donar suport a l'aplicació del programari lliure a l'Administració.

Més recentment, al 2013, la Índia va invertir en ordinador amb programari lliure (Ubuntu) per als seus estudiants.
És un dels programes més importants del món per a portàtils patrocinats pel govern, es porta a terme amb 1,5 milions d'ordinadors portàtils.

Respecte als formats i dades obertes, el 23 de juny del 2006, el Consell de Ministres de Bèlgica a Brussel·les va aprovar la decisió de requerir que tots els intercanvis documentals en els serveis del Govern Federal Belga es produeixin en formats oberts i estàndards.
Per tant, i expressament, només OpenDocument (ODF) va estar acceptat com a tal estàndard en aquesta decisió.

Al 2010 va néixer el projecte Open Data BCN, implantant el portal a l'any 2011, que té com a principal objectiu aprofitar al màxim els recursos públics disponibles, exposant la informació generada o custodiada per organismes públics, permetent el seu accés i reutilització per al bé comú i per al benefici de persones i entitats interessades.
El projecte que s'emmarca dins de l'estratègia Barcelona Ciutat Digital, es basa en els principals estàndards i recomanacions internacionals, adoptant les característiques, de dades obertes per defecte, qualitat i quantitat d'informació, dades per a tothom, dades per a la millora de la governança i promoció a la innovació.

Tal i com hem pogut veure en els casos que s'han descrit, des de fa molts anys les administracions estan desplegant un procés de transformació cap a metodologies àgils i programari lliure.
En algunes d'elles ja s'han pogut demostrar de forma clara els seus beneficis, tant a nivell d'estalvi econòmic i mitigació de la obsolescència tecnològica amb la incorporació de programari lliure, com en la millora de la productivitat i adaptació a través de les metodologies àgils.
