= Contexto
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== Ayuntamiento de Barcelona

El PBCD, aprobado el pasado mes de octubre del 2016, es un plan transversal con el que se pretende asegurar una política tecnológica coherente y homogénea dentro del Ayuntamiento en los ejes de gobierno y ciudad, empresas y entidades sociales y ciudadanía.

El PBCD debe asegurar que la tecnología y la innovación digital actúan de facilitadores en la consecución de unas políticas públicas equitativas y eficientes orientadas a cubrir mejor las necesidades de la ciudadanía y potenciar sus capacidades, para conformar unos servicios públicos de mayor calidad, con la óptima asignación y utilización de los recursos y el talento público.

Dentro del plan se han definido tres ejes estratégicos, con los siguientes objetivos (figura 1):

image::open-digit-p9-axes-{lang}.svg[FIGURA 1, align="center"]

El PTDA es la hoja de ruta de los proyectos TIC del mandato, global y para cada gerencia, de acuerdo con las prioridades políticas.
Este plan incluye también los proyectos de actualización tecnológica y los proyectos de adecuación al nuevo marco legal establecido por la Ley 39/2015, de 1 de octubre, de procedimiento administrativo común de las administraciones públicas.

== Marco Legal

La Ley 39/2015, de 1 de octubre, de procedimiento administrativo común de las administraciones públicas, que impulsa la Administración digital de una forma integral, tanto la relación con el ciudadano como la gestión electrónica del procedimiento administrativo, el documento y expediente electrónico, la interoperabilidad, etcétera, define un nuevo marco legal que obliga a hacer cambios profundos en la prestación de los servicios públicos y, en consecuencia, en la organización municipal y sus sistemas informáticos.

Hay que indicar que, además del cumplimiento de la mencionada ley, en el contexto normativo de la Unión Europea (UE), la legislación española y la catalana, encontramos también otros textos legales a los que también debe darse respuesta:

* El Plan de acción de Administración electrónica 2016-2020 de la UE, con el objetivo de eliminar los obstáculos digitales que se oponen al mercado único digital y evitar la fragmentación que se puede generar en el contexto de transformación de las administraciones públicas.

* El nuevo Reglamento general de protección de datos europeo, aprobado en mayo del 2016, al que se tiene que adaptar y que debe cumplir toda Administración pública.

* La Ley 19/2014, de 29 de diciembre, de transparencia, acceso a la información pública y buen gobierno.
Esta ley tiene por objeto facilitar a los ciudadanos el conocimiento de las actuaciones de las administraciones públicas autonómicas y el control y la transparencia en el destino del dinero público.

* La Ley 11/2007, de 22 de junio, de acceso electrónico de los ciudadanos a la Administración, conocida como LAESCP.
En este contexto, el software libre, los estándares y las tecnologías de fuentes abiertas están considerados la mejor opción para el desarrollo de un modelo tecnológico de e-Administración a la medida de las necesidades y los objetivos específicos de la Administración pública, basado en criterios estratégicos de transparencia, control, seguridad, interoperabilidad, acceso y conservación de la información, economía, reutilización o cooperación entre organizaciones, contra los que difícilmente pueden competir las tecnologías cerradas.

* Real decreto 4/2010, de 8 de enero, por el que se regula el Esquema Nacional de Interoperabilidad, que comprende los criterios y recomendaciones de seguridad, normalización y conservación de la información, de los formatos y de las aplicaciones que deberán tener en cuenta las administraciones públicas para asegurar un adecuado nivel de interoperabilidad organizativa, semántica y técnica de los datos, las informaciones y los servicios que gestionen en el ejercicio de sus competencias y para evitar la discriminación a la ciudadanía por su elección tecnológica.
Informaciones y servicios que gestionen en el ejercicio de sus competencias y para evitar la discriminación a los ciudadanos pera razón de su elección tecnológica.

== Nuevas tendencias en el desarrollo de servicios digitales ágiles, soberanía tecnológica y gestión ética de datos

En la situación actual, en que los cambios se producen de manera increíblemente rápida y en que se producen cambios dentro de los cambios, se necesitan modelos de desarrollo e implementación de servicios digitales que nos ayuden a adaptarnos a estas transformaciones.
Esta afirmación es mucho más acertada en el sector de las TIC, en el que la velocidad y la agilidad ante el cambio son fundamentales.
Por esta razón, y ante las dificultades y a veces fracasos experimentados con las metodologías tradicionales de gestión de proyectos, han surgido las metodologías ágiles.

Cuando se habla de metodologías ágiles, se hace referencia a un grupo de metodologías, de acuerdo con el “Manifiesto Agile”footnote:[_Manifesto ágil - font http://agilemanifesto.org_] del 2001, aplicadas en la creación de software que basa su desarrollo en un ciclo iterativo, en el que las necesidades y soluciones evolucionan mediante la colaboración entre los diferentes equipos involucrados en el proyecto.

Las metodologías ágiles promueven una gestión de proyectos disciplinada que fomenta la constante revisión y adaptación a las necesidades de los usuarios y a los cambios.
Proporcionan un sistema organizado que permite y facilita el trabajo en equipo y la autoorganización y favorecen la reducción del tiempo de desarrollo.

En referencia a la soberanía tecnológica y de datos, podemos afirmar que el software libre es “_técnicamente viable, económicamente sostenible y socialmente justo_” footnote:[_Jordi Mas, en su libro homónimo (Colección “Manuales y Formularios”, 15)._].
Eso se refleja en unos beneficios concretos en la Administración local.
////
A continuación se detallan estas tres características:
////

* Es *técnicamente viable* porque permite reaprovechar proyectos libres existentes, gracias a la reducción del esfuerzo de implementación para cubrir necesidades propias.
Toda empresa informática, con independencia de su tamaño, depende en mayor o menor grado de software libre.
Que la Administración local haga uso de él directamente es un paso lógico.

La libertad de escoger herramientas también significa libertad de proveedor para su mantenimiento y desarrollo.
Trabajar con formatos y estándares abiertos permite no depender de una gran empresa y tener acceso siempre a la información generada.

Participar directamente en la comuni-dad da acceso a conocimientos consolidados de otras entidades, y se puede contribuir con documentación o código o compartir experiencias implementando el proyecto en la Administración.

* Es *económicamente sostenible* porque elimina posibles licencias de uso y reduce costes.
Esta reducción no significa una pérdida de calidad ni de seguridad.
Al contrario, puede hacer viables proyectos que con software privativo no son posibles y mantener los sistemas actualizados y protegidos al menor coste posible.

El ahorro puede reinvertirse en _hardware_ adecuado para las nuevas herramientas o en partidas que necesiten recursos adicionales.
Así, la Administración local muestra responsabilidad hacia el dinero público y ejerce una gestión responsable.

Con la libertad de escoger proveedor sin restricciones se puede potenciar la reinversión del dinero público en el territorio, lo que favorece la economía de proximidad y genera un círculo virtuoso donde cualquier pyme, cooperativa y autónomo puede ofrecer sus servicios, en igualdad de condiciones.
En un país donde el 90 % de las empresas son pequeñas y medianas, eso abre un abanico de posibilidades muy amplio.

También permite escoger la gestión municipal de la infraestructura informática, sin necesitar especializaciones en herramientas privativas a altos costes.
La oferta laboral generada, pública o privada, será accesible a más profesionales del territorio.

* Es *socialmente justo* porque garantiza los derechos fundamentales de la ciudadanía.
El acceso al código fuente y su control colectivo ayuda a saber qué hace y a auditar que no tenga ninguna brecha o vulnerabilidad en cuanto a seguridad.
La privacidad y la seguridad de los datos quedan aseguradas.

Con el _software_ privativo, estos beneficios no existen o exigen costes económicos y sociales superiores

////
*Tendencias en estándares abiertos (e.g European Interoperability Framework, o Rd 4/2010)*
////

Desde el año 2010, existe el Real decreto 4/2010 (apartado 04.2), que obliga a las administraciones públicas a utilizar formatos abiertos a la hora de compartir información con la ciudadanía.
La lista de formatos no es una elección de cada entidad pública, sino que existe un listado de estándares tipificado y normalizado por su interoperabilidad.
Por lo tanto, las administraciones públicas utilizarán estándares abiertos con el fin de garantizar la independencia en la elección de alternativas tecnológicas para la ciudadanía y las administraciones públicas y la adaptabilidad al progreso de la tecnología.

Los documentos, servicios electrónicos y aplicaciones que las administraciones públicas han puesto a disposición de la ciudadanía o de otras administraciones públicas serán, según corresponda, visualizables, accesibles y funcionalmente operables, en condiciones que permitan satisfacer el principio de neutralidad tecnológica y que eviten la discriminación a la ciudadanía en razón de su elección tecnológica.

////
*Tendencias en gestión ética de datos*
////

Hasta hace poco tiempo los datos tenían una consideración residual y limitada, pero la capacidad de proceso informático nos ha llevado a poder aprovechar y reutilizar los datos.
Al mismo tiempo, estos datos han aumentado de manera exponencial.
Esta situación hace indispensable, por motivos de seguridad, un control de los datos y a la vez una liberación para potenciar su reutilización, con el convencimiento de que los datos públicos pueden generar negocio y mejora social para toda la población.
La combinación de herramientas libres y datos abiertos nos sitúa en un nuevo horizonte en el que la transparencia y la voluntad de compartir y trabajar de forma comunitaria generan una nueva organización de la Administración pública.

== Metodologías ágiles y software libre en otras administraciones públicas

*Metodologías ágiles*

El gran referente y pionero en la introducción de metodologías ágiles en las administraciones públicas fue el Gobierno británico footnote:[_https://www.gov.uk/service-manual/agile-delivery_], en el año 2010. Un buen ejemplo es el desarrollo del nuevo servicio de gestión de las inspecciones de automotores (parecidas a las ITV).

En un entorno más próximo, la Junta de Andalucía licitó en el año 2010 el servicio para el desarrollo del web “Consumo responde” mediante metodología ágil scrum.
También en el 2010 el Gobierno de Canarias licitó el servicio de mantenimiento del sistema informático de expedientes en el ámbito turístico mediante metodologías _scrum_.

El Ayuntamiento de Vitoria Gasteiz publicó en el 2013 un anuncio de licitación para “la contratación de rediseño del web municipal utilizando diseño adaptativo”.
En el pliego de prescripciones técnicas se especificaba que la metodología que utilizar es scrum, probablemente la más popular de las metodologías ágiles de desarrollo de _software_.

En marzo del 2017, la Diputación de Badajoz inició el procedimiento para la contratación de los servicios de desarrollo e implantación de nuevas funcionalidades, y la evolución tecnológica de sus actuales aplicativos de gestión utilizando metodología ágil _scrum_.

Instituciones público-privadas como el Museo Thyssen, el Hospital Clínico San Carlos, en Madrid, y su _Smart Health Lab_ o la Agencia Tributaria empiezan a usar y a aplicar técnicas ágiles como el _lean government_.

Barcelona empezó a introducir en el 2013 las metodologías ágiles para el desarrollo y la gestión de las webs municipales y ahora será la primera gran ciudad del sur de Europa en poner en marcha e implementar este tipo de metodologías de manera global en el Ayuntamiento.

*Tecnologías abiertas*

Con respecto a experiencias en software libre, en el ámbito local, encontramos el caso de la Universidad de Lérida (UdL), universidad pública pionera en el uso de _software_ libre en Cataluña.
Durante años ha utilizado sistemas libres con resultados excelentes.
En el 2003 accedió al rectorado un nuevo equipo que tenía como uno de sus objetivos potenciar el uso de _software_ libre, e inició un proceso de migración de todos los sistemas.

La Universidad de Murcia, en el 2014, se adscribió al proyecto Open Academic Environment (OAE), una iniciativa internacional para la creación de una plataforma de _software_ libre, que permite desarrollar una red académica colaborativa de carácter abierto.
Este proyecto está liderado por la Universidad de Cambridge, y la Universidad de Murcia ha sido la primera universidad española en participar.
En el 2015, inició la migración de sus equipos a Linux, hecho que les supuso un ahorro de 100.000 euros en licencias y de otros 300.000 euros, al evitar tener que renovar equipos.

En el ámbito internacional, el Ministerio de Exteriores alemán, en el 2003, inició la migración de sus 11.000 ordenadores a GNU/Linux y a aplicaciones de _software_ libre.
Eso ha permitido reducir considerablemente los costes, si los comparamos con otros ministerios.
Se pretende que la migración se lleve a cabo en las 230 embajadas y consulados repartidos por todo el mundo.

En Italia, en el 2014, se escogió el _software_ libre como primera opción para la Administración pública.
Crearon un documento titulado “Guías para la evaluación comparativa (de _software_)”, con el que se aprende un método para tomar la decisión correcta a la hora de escoger un software.
El caso italiano es muy importante porque se preocupa no solo por la norma, sino por su implementación.
La guía elaborada por la Agencia Digital Italiana se redactó con participación tanto de la FSFE como de los representantes de diferentes empresas de _software_ privativo.

Las políticas de tecnologías abiertas para la administración pública europea son apoyadas para la acción de la Comisión Europea, que publica a su propia licencia libre para Administraciones Públicas, la licencia EUPL, y centraliza los esfuerzos en su plataforma “_Join Up_” donde encontramos literalmente centenares de experiencias de migración o desarrollo de _software_ libre a las administraciones europeas.

En Brasil, el Gobierno inició en paralelo diversos proyectos de inclusión digital en diferentes zonas, basados en el establecimiento de telecentros, con el objetivo de reducir la exclusión digital, aumentar la capacidad profesional, difundir el software libre y aumentar la participación popular en las nuevas tecnologías.
El software libre ha jugado un papel fundamental en la creación de estos centros y está permitiendo que los recién llegados al mundo digital puedan hacerlo con _software_ legal.

El 16 de julio de 2004, la Administración pública de Malasia inició el Plan maestro para fomentar, adoptar y desarrollar el uso del _software_ libre en el sector público.
Se puso en marcha el Open Source Competency Center (OSCC), que se estableció como centro de referencia nacional para dirigir y apoyar la aplicación del _software_ libre en la Administración.

En diciembre del 2013, la India invirtió en ordenadores con _software_ libre (Ubuntu) para sus estudiantes.
Es uno de los programas más importantes del mundo para portátiles patrocinados por el Gobierno, y se lleva a cabo con 1,5 millones de ordenadores portátiles.

El 23 de junio de 2006, el Consejo de Ministros de Bélgica en Bruselas aprobó la decisión de requerir que todos los intercambios documentales en los servicios del Gobierno federal belga se produzcan en formatos abiertos y estándares.
Por lo tanto, y de manera expresa, solo OpenDocument (ODF) estuvo aceptado como tal estándar en esta decisión.

En el 2010 nació el proyecto Open Data BCN (el portal se implantó en el año 2011), cuyo principal objetivo es aprovechar al máximo los recursos públicos disponibles, exponiendo la información generada o custodiada por organismos públicos, permitiendo su acceso y reutilización para el bien común y para el beneficio de personas y entidades interesadas.

En el año 2004, el equipo de TI de la Gendarmerie Nationale, con el fin de poder ofrecer un servicio responsable y rentable de alcance nacional y para reducir los crecientes costes de infraestructura de TI, decidió revisar su entorno basado en Microsoft existente. Migró a OpenOffice, Firefox, e hizo una actualización de PC hacia Ubuntu, lo que supuso un ahorro de 2 millones de euros anuales solo en derechos de licencia y una reducción drástica de los gastos en hardware.

El proyecto, que se enmarca dentro de la estrategia “Barcelona, ciudad digital”, se basa en los principales estándares y recomendaciones internacionales, y adopta las características, de datos abiertos por defecto, calidad y cantidad de información, datos para todo el mundo, datos para la mejora de la gobernanza y promoción de la innovación.

Tal como hemos podido ver en los casos que se han descrito, desde hace años las administraciones están viviendo un proceso de transformación hacia metodologías ágiles y _software_ libre.
En algunas de ellas ya se han podido demostrar de forma clara sus beneficios, tanto con respecto al ahorro económico y la mitigación de la obsolescencia tecnológica con la incorporación de _software_ libre, como con respecto a la mejora de la productividad y la adaptación mediante las metodologías ágiles.

////
Ordre diferent amb titols diferents
////
