= Gobernanza del proceso de digitalización
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

Esta transformación es un proceso largo que requiere de la implicación de la Administración, así como del sector TIC y de la sociedad.
Con el fin de que este proceso alcance sus objetivos y se ajuste al calendario establecido deberá disponer de una gobernanza específica.

Para la gobernanza de este proceso se utilizarán diversos instrumentos, entre los que se pueden destacar el Comisionado de Tecnología e Innovación Digital, la Comisión de Transformación Digital de Barcelona y la Ponencia de Innovación, sin olvidar al resto de agentes de la ciudad, como empresas o representantes de la sociedad civil.

Los principales elementos de gobernanza son los siguientes:

* *Comisionado de Tecnología e Innovación Digital.*
Una de sus misiones es rediseñar y reorientar la tecnología de Barcelona y las estrategias y políticas de innovación digital a través de un proceso con participación activa de actores clave de la ciudad.
Dos de sus principales ejes son la digitalización de los servicios públicos y el impulso del ecosistema innovador digital, que incluye la relación entre las administraciones públicas, la ciudadanía, las empresas y el mundo académico.
El comisionado dispone de una oficina de seguimiento e impulso de proyectos que debe asegurar la coordinación municipal y medir el impacto de la implementación de este programa.

* *Comisión de Transformación Digital de Barcelona.*
Es un instrumento municipal transversal creado para gobernar la definición y ejecución del PTDA y asegurar su alineación con la estrategia del Ayuntamiento.
Además de su función principal de priorizar y coordinar las iniciativas TIC del Ayuntamiento, también analizará la situación y evolución del programa de digitalización y constituirá un espacio de debate, discusión y propuesta entre los diferentes ámbitos y sectores municipales.

* *Ponencia de Innovación Digital.*
Es un instrumento municipal transversal a las diferentes áreas del Ayuntamiento, encargado de hacer operativo el diseño y la implementación de la estrategia y las políticas de innovación.
Su función será, entre otras, asegurar la implicación y la alineación de las diferentes áreas municipales en este proceso.
