= Introducción i justificación de la medida
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

La era digital está modificando la sociedad de forma profunda y rápida y, por lo tanto, el modelo de relación de los ciudadanos con las empresas y las administraciones públicas.
La convergencia entre la transformación digital, la participación ciudadana y la transparencia obliga a cambiar los modelos de los organismos públicos para que tengan la capacidad de adecuarse a las nuevas necesidades creadas.
Esta transformación representa un gran reto con respecto al Ayuntamiento, con una actividad muy regulada por condicionantes legales, económicos y de recursos humanos.

Programa para la digitalización abierta: con _software_ libre y desarrollo ágil de servicios del Ayuntamiento de Barcelona se quiere proporcionar una orientación enfocada al servicio y a la soberanía tecnológica para revitalizar la totalidad del Consistorio, consolidando el gobierno de los servicios digitales, generando perfiles y capacidades en _software_ libre y de código abierto y uso ético de los datos y transformando la contratación pública.
La implementación de este enfoque, basado en metodologías ágiles y uso de tecnologías abiertas, ha demostrado eficiencias en términos de prestación (_performance_) y costes que el Ayuntamiento debe aprovechar.

En esta línea, abre la contratación pública y la hace más transparente, sencilla y objetiva, lo que genera las condiciones para la participación de un conjunto diversificado de industria local de talento y potencia las pequeñas y medianas empresas del país.
Al mismo tiempo se revisan, también, los procesos contractuales actuales para asegurar la soberanía tecnológica y de los datos.
Los procedimientos de contratación también deben transformarse con el fin de acercarlos a la realidad de los servicios ofrecidos a la ciudadanía y hacer posible que estas medidas se puedan aplicar.

Para alcanzar el objetivo principal y transformar el Ayuntamiento de Barcelona en una entidad líder en la digitalización del sector público, se deben definir los pasos necesarios para avanzar y construir servicios públicos “digitales por defecto” en Barcelona, abiertos, más sencillos, modulares, interoperables y que procurarán evitar bloqueos con proveedores de soluciones propietarias.
