= Líneas de actuación
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

Sobre cada uno de los temas que se han indicado en el apartado anterior se han establecido unas líneas de actuación, que ampliamos a continuación, junto con sus acciones asociadas.

== Servicios digitales ágiles y centrados en el usuario

Para el desarrollo de los servicios digitales centrados en los usuarios es imprescindible la introducción de las metodologías de desarrollo ágil.

Durante el primer semestre del 2017 se han organizado cuatro talleres (herramientas, gestión ágil, capacitación y cultura y organización) con personal interno del IMI, desarrolladores, responsables de servicio, responsables sectoriales y directivos.

Con la implantación de estas metodologías se alcanzarán las líneas de actuación establecidas:

* Barcelona transformará 20 nuevos servicios digitales (descritos en el apartado 0.8), según el Estándar de servicios digitales y el Codigo de prácticas tecnológicas.

* Centrarse más en el usuario final, dando más protagonismo a la *toma de decisiones*.

* *Acortar el tiempo de desarrollo* mejorar a la vez la cualidad técnica.

* *Ofrecer más valor público* todo manteniendo el control de los desarrollos.

A partir de las líneas de actuación identificadas, se alcanzarán los siguientes objetivos:

* Transformar la cultura organizativa, promoviendo la colaboración y la transparencia, siendo más flexibles y entregando más valor público.

* Implementar la mejora continua introduciendo en la organización las prácticas que deben hacer que los procesos de mejora sean sistémicos.

== Soberanía tecnológica y migración a _software_ libre

La consecución de la soberanía tecnológica se hará a través de la migración a software libre, el despliegue de estándares abiertos, los cambios en la contratación pública para fomentar el software de código abierto y la identificación de oportunidades de migración a arquitecturas abiertas a corto plazo.

Las líneas de actuación hacia este tema son las siguientes:

* *Lograr que el 70 % de la inversión* en nuevos desarrollos de software se haga con código abierto.

* Poner a disposición de otros municipios y administraciones *diez soluciones* desarrolladas por el Ayuntamiento de Barcelona.

* Incorporar la estación corporativa abierta basada en sistemas y programas abiertos al parque municipal.

Durante el primer semestre del 2017 se ha estado trabajando en las siguientes acciones:

* Identificar oportunitats de desenvolupament i/o migració a arquitectures i sistemes oberts a curt termini.

* Preparació d'un pla de migració i desenvolupament de codi lliure i de codi obert.

* Definició de pautes per a publicar i compartir programari i continguts de l'Ajuntament sota llicències de programari i continguts lliure.

* Introduir en la contractació pública el foment de la creació, ús i reutilització del programari lliure i de codi obert.

* Introduir les directrius a nivell corporatiu per a l'ús d'estàndards oberts per a les tecnologies, dades i altres informacions de la ciutat.

A partir de les línies d'actuació identificades, s'aconseguirà:

* Increment de la sobirania tecnològica.

* Millora de la imatge i posicionament davant de la societat.

* Reducció costos desenvolupament (pocs d'entrada).

* Reducció costos manteniment (efectiu).

* Reducció costos evolutius (notable quan introduïm noves funcionalitats desenvolupades per la comunitat).

* Reducció costos migració a noves solucions (important).

Els projectes emblemàtics en aquest tema, amb un pressupost total de 21,5 milions d'euros i un calendari que va des de el primer trimestre de 2017, fins al final del segon trimestre del 2019, s'inclouen al Pla de Migració a Codi Obert (annex 12.5).

* Migració del correu corporatiu a tecnologies obertes.

* Adaptació de l'estació de treball Windows (Windows 10) amb conjunt d'aplicacions de programari lliure.

* Adopció d'eines per al desenvolupament d'aplicacions basades en tecnologies obertes.

* Estació de treball i escriptori obert.

* Identificador Mobile-ID / e-ID.

* Nous serveis desenvolupats en codi obert.

== Estrategia responsable y ética de datos

Los datos toman una relevancia considerable en el entorno municipal y de ciudad y se hace patente la necesidad de definir y poner en marcha un nuevo modelo transversal de gobierno de los datos que refuerce la soberanía

////
Indiquem aquí les línies d'acció i projectes que cauran sota l'àmbit d'aquesta pròxima mesura, element essencial del Pla de Transformació Digital.
////

Las líneas de actuación hacia este tema son las siguientes:

* *Disseny i execució* de les accions d'adaptació al nou RGPD pel tractament de les dades de caràcter personal a l'ajuntament de Barcelona.

* *Definición e implantación* de los nuevos procesos que permitan la incorporación de la privacidad y la seguridad por defecto y desde el diseño en los nuevos aplicativos informáticos.

* *Establecimiento del control* proactivo que pide la nueva normativa.

* Definición de la oficina municipal de análisis de datos y de la figura del *_Chief Data Office_*.

* Creació de la figura *Chief Data Analytics Office* que aporti noves capacitats relacionades amb la millora de dades i l'anàlisi de les mateixes en la protecció de la privacitat interna.

////
* Crear un programa “*Data Challenges*” per involucrar a les pimes i empreses en la creació d'aplicacions basades en dades per resoldre els reptes de la ciutat.
////

Durante el primer semestre del 2017 se ha estado trabajando en las siguientes acciones:

* Establecer las nuevas reglas para el gobierno de datos.

* Definir una arquitectura abierta de datos.

* Crear plataformas para el análisis masivo de datos para políticas y servicios públicos.

* Elaborar una guía para el uso ético y responsable de los datos, garantizando privacidad y soberanía.

A partir de las líneas de actuación identificadas, se alcanzarán los siguientes objetivos:

* Mejorar la eficacia y la eficiencia.

* Millorar la presa de decisions.

* Democratizar el acceso a los datos.

* Crear nuevos y mejores servicios públicos.

* Conseguir calidad democrática.

* Generar transparencia y rendición de cuentas.

* Recuperar la confianza de la ciudadanía.

Los proyectos emblemáticos en este tema, con un presupuesto total de 2,3 millones de euros y un calendario que va desde el primer trimestre del 2017 hasta mediados del primer trimestre del 2019 son los siguientes:

* Servicios City OS (contaminación, movilidad, turismo).

* Cuadro de mandos de ecología.

* Observatorio de la Vivienda de Barcelona (OVB).

* DCODE: Projecte de tota la UE per desenvolupar una arquitectura basada en blockchain (cadena de blocs) per a la sobirania de dades.

== Nuevo modelo de contratación

Con la consecución del objetivo principal del nuevo modelo de contratación, indicado en el apartado 6.5, se podrá garantizar la soberanía tecnológica y de los datos, se fomentará la innovación tecnológica y se hará palanca en la transformación socioeconómica.

Las líneas de actuación hacia este tema son las siguientes:

* *Doc. _Framework_:* conceptualización de la nueva orientación en la contratación.

* *•Guía de compra de TIC:* Guía que facilita una visión global de la estrategia municipal y la aplicación de las diferentes medidas.

* *Guía de compra de innovación:* guía que orienta al lector a considerar la innovación como elemento fundamental indisociable y potenciador de las compras sostenibles.

* *Pliegos tipo:* estandarización y agilidad en la contratación.

* *_Marketplace:_* espacio de diálogo continuo e interrelación entre proveedores, la ciudadanía y el Ayuntamiento.

* *Comunicación y difusión:* acciones de difusión sobre el proceso de transformación y la estrategia municipal con respecto a la contratación.

Durante el primer semestre del 2017 se han organizado:

* La guía de compra de tecnología y la guía de compra de innovación.

* Se ha iniciado ya la preparación de los pliegos tipo.

* S'han organitzat sessions de treball amb el sector TIC per l'enriquiment de les mesures vinculades a la compra de tecnologia.

* Se han hecho prospecciones para construir una plataforma de mercado digital (_marketplace_).

El proyecto emblemático en este tema, con un presupuesto total de 22 millones de euros y un calendario que va desde el inicio del segundo trimestre del 2017 hasta finales del primer trimestre del 2018 es el siguiente:

* Conceptualización de un _marketplace_.

== Cultura y organización del cambio

Para la transformación de los equipos existentes se está realizando entre otras actuaciones, una plan de capacitación del personal interno, con talleres orientados a la organización, la capacitación y la cultura, la gestión ágil y el aprendizaje de herramientas.

De forma paralela, en el primer semestre de 2017 también se ha iniciado un proceso de cobertura de 64 nuevas plazas de técnicos informáticos (superiores y medios), a través de 2 bolsas de trabajo.
Se prevé que este proceso durará hasta finales de 2017 y la incorporación de las personas se realizará durante el primer semestre del 2018.

También está prevista una reestructuración orgánica que prevé la creación de 16 nuevos departamentos, de acuerdo con criterios de diferenciación por ámbitos sectoriales para especialización técnica, que reforzará el mando, la asunción de responsabilidades por los mandos intermedios y la coordinación de los diferentes grupos de trabajo.

Para finalizar, indicaremos que los proyectos emblemáticos que se han apuntado en cada una de las líneas de actuación y que se detallan en el apartado 08, forman parte del Plan de Mandato que se conforma de 3 planes:

Sectorial, de Ley y Tecnológico, tal y como se refleja a continuación (Figura 4).
También podemos observar el estado de ejecución de los mismos, así como el grado de ejecución del presupuesto de 2017.

image::open-digit-p30-roadmap-{lang}.svg[ align="center" _FIGURA 4: Composición y ejecución del Plan de Mandato_]
