= Mètriques d'èxit i resultats
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

El propòsit de les mètriques d'èxit és proporcionar eines per comprendre si les accions realitzades per l'Ajuntament l'han acostat als seus objectius i quins canvis s'han de realitzar en el que s'està fent per l'assoliment dels mateixos.
Una mètrica ben dissenyada, contesta les preguntes de rendiment específiques i permet prendre decisions de millora de serveis basades en dades.

Es monitoritzarà el progrés del programa de digitalització a través dels projectes emblemàtics.
D'aquests es mesurarà el seu grau d'execució (% d'execució) i el pressupost executat.
El progrés de les diferents línies d'actuació del programa i les iniciatives que comprenen es mesurarà mitjançant mètriques i indicadors d'avanç específics per a cada iniciativa: proporció de contractes desenvolupats en metodologies àgils, pressupost destinat a projectes àgils, pressupost destinat a projecte de programari lliure i de codi obert, temps de desenvolupament i posta en marxa de nous serveis, quantitat de defectes detectats en els desenvolupaments, nombre d'iteracions, etc.

Es mesurarà el nivell de coneixement del procés de transformació que es té des de les diferents àrees municipals.
A la vegada, s'avaluarà el grau de satisfacció de cada àrea amb els nous serveis digitals desenvolupats, mitjançant una enquesta periòdica.
En la mateixa enquesta es mesurarà l'ajust dels serveis a les necessitats del “negoci”, el grau d'actualització dels mateixos, la seva usabilitat, accessibilitat, grau d'innovació i temps de resposta.

Una altra mètrica important que s'utilitzarà per monitoritzar l'èxit del programa, és la disponibilitat dels serveis públics digitals.
En el següent gràfic (Figura 6), es mostren els resultats respecte disponibilitat i prestació de serveis del primer semestre del 2017.

image::open-digit-p34-pki-{lang}.svg[_FIGURA 6: Indicadors de disponibilitat de serveis_]

Finalment, els recursos humans és un dels altres principals indicadors que s'utilitzaran per a mesurar el progrés d'aquest programa.
El procés que s'està portant a terme en aquest àmbit, així com la planificació, queda reflectida en la següent imatge (Figura 7).

image::open-digit-p35-resources-{lang}.svg[_FIGURA 7: Indicadors del Pla de recursos humans_]
