= Métricas de éxito y resultados
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

El propósito de las métricas de éxito es proporcionar herramientas para comprender si las acciones realizadas por el Ayuntamiento lo han acercado a sus objetivos y qué cambios deben realizarse para su consecución.
Una métrica bien diseñada responde las preguntas de rendimiento específicas y permite tomar decisiones de mejora de servicios basadas en datos.

Se monitorizará el progreso del programa de digitalización a través de los proyectos emblemáticos.
De estos se medirá su grado de ejecución (% de ejecución) y el presupuesto ejecutado.
El progreso de las diferentes líneas de actuación del programa y las iniciativas que comprende se medirán mediante métricas e indicadores de avance específicos para cada una: proporción de contratos desarrollados con metodologías ágiles, presupuesto destinado a proyectos ágiles, presupuesto destinado a proyectos de software libre y de código abierto, tiempo de desarrollo y puesta en marcha de nuevos servicios, cantidad de defectos detectados en los desarrollos, número de iteraciones, etcétera.

Se medirá el nivel de conocimiento del proceso de transformación que hay en las diferentes áreas municipales.
A la vez, se evaluará el grado de satisfacción de cada área con los nuevos servicios digitales desarrollados mediante una encuesta periódica.
En dicha encuesta se medirá el ajuste de los servicios a las necesidades del “negocio”, su grado de actualización, usabilidad, accesibilidad, nivel de innovación y tiempo de respuesta.

Otra métrica importante para monitorizar el éxito del programa es la disponibilidad de los servicios públicos digitales.
En el siguiente gráfico (figura 6) se muestran los resultados con respecto a disponibilidad y prestación de servicios del primer semestre del 2017.

image::open-digit-p34-pki-{lang}.svg[_FIGURA 6: Indicadors de disponibilitat de serveis_]

Finalmente, los recursos humanos son otros de los principales indicadores que se utilizarán para medir el progreso de este programa.
El proceso que se está llevando a cabo en este ámbito, así como su planificación, quedan reflejados en la siguiente imagen (figura 7).

image::open-digit-p35-resources-{lang}.svg[_FIGURA 7: Indicadors del Pla de recursos humans_]
