= Objetivos de la medida
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

La medida expone el Programa de digitalización abierta y desarrollo ágil de servicios del Ayuntamiento de Barcelona y se centra en los objetivos indicados en el apartado anterior.
Finalmente se presentan los proyectos emblemáticos a través de los que se empiezan a implantar estas nuevas prácticas.

Así pues, los objetivos principales de esta medida son conseguir que el Ayuntamiento sea capaz de desarrollar de forma ágil servicios digitales centrados en las necesidades reales de la ciudadanía; alcanzar una independencia tecnológica basada en _software_ libre y el uso de estándares abiertos; poner a disposición de los ciudadanos datos de la Administración pública para que puedan obtener más valor, y asegurar que puedan acceder a estos servicios salvaguardando el derecho a la privacidad.
A continuación se detallan estos y otros objetivos de la medida:

. Desarrollar un modelo de servicios digitales centrado en el usuario y más colaboración para generar más valor con los mismos recursos.

. Generalizar y extender metodologías ágiles para la construcción de nuevos servicios públicos digitales.

. Desarrollar las capacidades internas para la gestión ágil de los servicios públicos en todo el Ayuntamiento.

. Hacer que la contratación pública sea más transparente, sencilla y objetiva.

. Utilizar preferentemente _software_ libre y abierto, con el propósito de que su uso sea obligatorio en el futuro para asegurar la soberanía tecnológica y de los datos.

. Establecer una arquitectura abierta y prácticas basadas en estándares abiertos.

. Revisar los procesos de contratación para incorporar estos objetivos e innovaciones a las relaciones con el sector industrial.

. Mejorar el acceso a datos de la Administración, respetando la privacidad y evaluando los riesgos éticos de la ciudad inteligente y las grandes bases de datos, incluido el cumplimiento legal de la normativa de protección de datos, configurando un código ético de práctica tecnológica y definiendo una estrategia de datos.

. Desarrollar nuevas guías de adquisición de tecnología que se integrarán en el marco general del contrato público, que todos los contratos públicos y funcionarios administrativos del Ayuntamiento deberán seguir e implementar.

////
Finalment es presenten els *projectes emblemàtics*, a través dels quals es comencen a assolir aquests objectius i a implantar les noves pràctiques necessàries per a fer-ho.
////
