= El Programa de digitalización abierta y entrega ágil de servicios
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== Declaración y principios de la misión

*Actualmente, los servicios públicos deben diseñarse “digitales primero”, y poner a la ciudadanía en el centro del proceso de diseño y aportar más valor público.*
*Los servicios deben construirse de forma más ágil y, al mismo tiempo, abierta; tienen que ser más sencillos, modulares e interoperables.*
*También hay que evitar dependencias con vendedores y proveedores de soluciones propietarias específicas, por lo que es necesario potenciar el desarrollo, el uso y la reutilización del software libre y de código abierto y estándares abiertos.*
*Los servicios tienen que ser usables y accesibles a todo el mundo, incluida aquella parte de la ciudadanía con menos destreza para el mundo digital y las personas con cualquier tipo de discapacidad.*

El *Programa de digitalización abierta y desarrollo ágil de servicios* proporciona una orientación enfocada al servicio digital para revitalizar el Ayuntamiento como referente para la innovación y la excelencia tecnológica.
Aportará servicios digitales de calidad, ajustados a las necesidades de los ciudadanos y orientados a salvaguardar el derecho a la privacidad de la ciudadanía (privacidad de los datos), servicios que, haciendo uso del software libre y de código abierto y estándares abiertos, romperán la dependencia de formatos, productos y soluciones propietarias (soberanía tecnológica).

Los servicios públicos digitales deben convertirse en verdaderos activos de la sociedad actual y deben posibilitar su reutilización en otras ciudades.
Y para ello son necesarias actuaciones también en el ámbito de la compra pública de tecnología que fomenten un enfoque más maduro para el abastecimiento de tecnología en el sector público, proponiendo modelos de contratación multiproveedor que promuevan la competencia y la diversidad de proveedores, que faciliten la adopción de nuevas tecnologías innovadoras y que se alejen de los grandes contratos, para crear así un nuevo mercado para pymes abierto y colaborativo.

Al mismo tiempo, el programa genera perfiles y capacidades en diseño centrados en el usuario y metodologías ágiles para flexibilizar y acelerar el desarrollo y la ejecución de estos servicios, a la vez que abre la contratación pública y la hace más transparente, sencilla y objetiva, con lo que se proporciona un camino hacia la soberanía tecnológica y de los datos.

El programa, que establece un marco para obtener una arquitectura abierta y diseños basados en estándares abiertos, se implementará mediante un conjunto de cambios incrementales con una clara estructura de gobierno, orientados a resultados, con métricas e indicadores claros y una hoja de ruta compartida.

Como punto de partida, el programa define los principios básicos que deben guiar el desarrollo de los nuevos servicios.
Estos principios quedan recogidos en el decálogo “*Nuestros estándares de servicios digitales*” (véase el anexo 12.1): que puede diseñar, construir y hacer operativo el servicio, liderado por un responsable de servicio sénior cualificado para este trabajo y que tiene responsabilidad para tomar decisiones.

* *Empezar con las necesidades de los usuarios.*
Es imprescindible entender las necesidades del usuario e investigar para desarrollar más conocimiento sobre quiénes son los usuarios del servicio y lo que ello significa para el diseño del servicio.

* *Empezar con las necesidades de los usuarios.*
Es imprescindible entender las necesidades del usuario e investigar para desarrollar más conocimiento sobre quiénes son los usuarios del servicio y lo que ello significa para el diseño del servicio.

* *Utilizar metodologías de desarrollo ágil y construir de manera iterativa.*
Construir el servicio utilizando métodos ágiles, iterativos y centrados en los usuarios.

* *Reducir la carga sobre la ciudadanía.*
Se utilizará la información ya existente en los seis temas municipales en las nuevas interacciones con los ciudadanos y se interoperará con otras administraciones públicas para reunir la información necesaria y evitar tener que pedir a la ciudadanía que la vuelvan a aportar.
Se eliminarán los documentos innecesarios en la versión digital del servicio y el Ayuntamiento se asegurará de que la ciudadanía da su consentimiento para el uso de sus documentos personales.

* *Seguir las directrices sobre diseño visual y accesibilidad.*
Se construirá un servicio coherente con la experiencia de las personas usuarias del resto del Ayuntamiento de Barcelona, a propósito de las directrices de diseño visual y de accesibilidad existentes.

* *Disponer de un plan para las personas que necesitan ayuda digital. Se fomentará entre todos los usuarios el uso del servicio digital.*
También se confeccionarán planes para las personas que por cualquier razón no pueden acceder a los servicios digitales sin ayuda.
En el caso de prestar un servicio esencial, habrá que asegurar que el Ayuntamiento se adapte a aquella parte de la ciudadanía que no tiene dispositivos digitales.

* *Pensar en la seguridad, la privacidad y los aspectos éticos.*
Se evaluará qué datos de las personas usuarias y qué información se proveerá o almacenará en el servicio digital, y se trabajará en el nivel de la seguridad, las responsabilidades legales, los asuntos de privacidad y los riesgos asociados con el servicio (se consultará con expertos, en su caso).

* *Se utilizará software abierto y estándares abiertos.*
Se utilizará software abierto y estándares abiertos siempre que sea posible.
Asimismo, se hará que todo el nuevo código sea abierto y reutilizable para que se publique bajo las licencias adecuadas.

* *Disponer de un plan para ser digitales.*
Habrá que asegurar que los servicios digitales proporcionen medios digitales a los ciudadanos con el fin de proveer, firmar y verificar sus documentos.
En caso de que haya ciudadanos que no puedan proveer recursos digitales por ellos mismos, habrá que garantizar que hay un servicio disponible en el Ayuntamiento con el fin de digitalizar estos documentos.

* *Hacer un plan para estar fuera de línea en caso de imprevistos.*
Se dispondrá de un plan para cuando el servicio digital pueda estar temporalmente inoperativo, ya que las personas usuarias esperarán que un servicio en línea esté disponible las 24 horas del día, los 365 días del año.

* *•Se evaluarán las herramientas, los sistemas y los servicios.*
Se hará una evaluación para asegurar que se sigue el código tecnológico de conducta y se entienden los riesgos técnicos asociados.

* *Reutilización de la infraestructura existente y de las funciones compartidas en la medida en que sea posible.*
Se creará una experiencia de servicio coherente que permita ahorrar tiempo y recursos de la reconstrucción de funcionalidades ya existentes.

* *Definición de un plan de gestión del cambio para la transición del servicio.*
Habrá planes de servicios de continuidad para facilitar la transición entre el servicio no digital actual y el nuevo servicio digital.
Se tiene que evitar cualquier interrupción en el acceso al servicio por parte de la ciudadanía.

* *Escucha y evaluación continua del usuario.*
Se establecerá un plan para la escucha continua de las personas usuarias y la realización de pruebas de usabilidad, con el fin de recoger de forma continuada la opinión de los usuarios y poder mejorar así el servicio.

* *Medir y publicar el resultado del servicio.*
Se identificarán los indicadores de cumplimiento del servicio, estableciendo un punto de referencia para cada métrica y haciendo un plan para permitir mejoras.

* *Hacer un plan para el mantenimiento y el servicio del servicio digital.*
Habrá un plan de “respuesta y escalada” para reducir al mínimo la interrupción del servicio cuando se produzcan incidentes.

El Ayuntamiento de Barcelona ha editado un póster informativo con información más detallada para la divulgación de nuestros estándares de servicios digitales.
Este póster se puede ver en el anexo 12.1 que acompaña a esta medida.

== Prioridades y métodos para la creación de servicios digitales

Para el mejor desarrollo del programa de digitalización y para obtener servicios digitales públicos, abiertos, interoperables, éticos y ágiles se han identificado las siguientes cuatro grandes áreas de actuación:

* Metodologías ágiles en la entrega de servicios digitales.

* Soberanía tecnológica (software libre y estándares abiertos).

* Soberanía y uso responsable de los datos.

* Nuevo modelo de contratación pública.

Cada área de actuación será liderada por un equipo diferente.
Se priorizará la creación de un estándar de servicios, el código de prácticas tecnológicas, la guía para la introducción de las metodologías ágiles, la guía para la transición al _software_ libre y de código abierto (_software_, hardware, sistemas), la estrategia de datos y la guía de contratación pública abierta.

Esta es una transformación interna y, por lo tanto, el proceso debe ser liderado desde el propio Ayuntamiento, implicando al equipo humano y trabajando para evolucionar la capacidad para adquirir habilidades y resultados.
Puntualmente será necesario el apoyo de expertos externos del sector que, junto con la formación y el rodaje de los nuevos equipos ágiles, ayudarán a comprender las capacidades y competencias que se necesitarán en un futuro inmediato.
Se desarrollará un plan de contratación y un programa de creación de habilidades para hacer frente a estas necesidades y poder mantener la transformación viva.
Este proceso generará una fuerte implicación interna.

Todo el proceso de transformación se llevará a cabo siguiendo la misma filosofía ágil.
Así, se inicia con una fase de descubrimiento seguido de las sucesivas iteraciones que permitirán ir introduciendo de forma gradual la nueva cultura y las nuevas prácticas.

Se desarrollarán y refinarán las nuevas prácticas a partir de proyectos reales, que denominaremos _ejemplares_ o _emblemáticos_ (descritos en el apartado 8 de este documento).
La nueva metodología se irá extendiendo de forma gradual a todos los proyectos donde estas prácticas sean de aplicación.

== Situación actual

El pasado mes de setiembre del 2016 se inició el proceso de descubrimiento en el Ayuntamiento de Barcelona con el apoyo de expertos externos.
Se crearon cuatro grupos de trabajo en los que participaron más de cuarenta trabajadores de diferentes áreas municipales.
Durante cuatro meses, estos grupos estuvieron trabajando con la ayuda de cuatro personas expertas externas con el objetivo de generar una base propiciatoria para el impulso del cambio.

A lo largo del 2017, se han realizado hasta tres sesiones con el sector (programación y tecnologías abiertas, servicios digitales ágiles y compra pública de tecnología), en las que se han implicado más de doscientos representantes.
De manera interna, entre abril y junio de este año, dentro del Plan de transformación se organizaron cuatro talleres (taller de herramientas, taller de gestión, taller de capacitación y taller de organización).

En el primer trimestre del 2017 se ha aplicado la metodología ágil a un primer proyecto real, el cuadro de mandos de la gerencia municipal.
Esto ha servido para definir las actuaciones de introducción de las metodologías ágiles en el Ayuntamiento, escoger los proyectos más adecuados donde empezar a aplicarlas, identificar el apoyo externo necesario, definir el plan de capacitación interna, la organización y las herramientas necesarias para las nuevas prácticas.

El Ayuntamiento, entre los años 2016 y 2017, puso en funcionamiento Decidim Barcelona y Sentilo BCN, aplicaciones ya desarrolladas con software propio.

* *Decidim Barcelona* es el proyecto de software libre más avanzado del Ayuntamiento de Barcelona y ha permitido una de las mayores participaciones ciudadanas abiertas, transparentes y trazables del mundo en la construcción colectiva de un plan estratégico de ciudad.
Su misión es dar apoyo, abrir y amplificar la participación y la democracia en Barcelona para los próximos años, avanzando hacia una mayor capacidad de colaboración entre el Ayuntamiento y la ciudadanía, una mayor autonomía de las personas en la toma de decisiones, con especial énfasis en la dimensión colectiva y, en definitiva, en la producción y distribución del poder social, principios que continúan hoy también vigentes en gran parte de las comunidades de _software_ libre.

* En referencia a la plataforma de sensores de Barcelona, *Sentilo BCN*, desarrollada íntegramente con software libre y ofrecida en el mundo a través de la comunidad Sentilo, ya se está utilizando en diferentes ciudades y administraciones públicas y un gran número de ciudades y empresas han mostrado su interés por instalarse la web de Sentilo.
El principal objetivo de Sentilo es proporcionar a todas las ciudades del mundo que lo deseen una plataforma funcional, abierta, interoperable y fácilmente ampliable, compartiendo la inversión pública del desarrollo bajo el modelo de software libre.
La comunidad Sentilo quiere ser además un lugar de encuentro donde ciudades y empresas puedan colaborar para mejorar la plataforma, proporcionar apoyo o desarrollar negocios en torno a Sentilo.
Las organizaciones que, además de Barcelona, están utilizando Sentilo en la actualidad son las siguientes: Terrassa, Reus, Cambrils, Diputación de Barcelona, Agencia Catalana del Agua (ACA), Área Metropolitana de Barcelona (AMB) y la municipalidad de Dubái.

////
En l'àmbit de les dades obertes, cal destacar, el portal *Open Data BCN* o servei de dades obertes de l'Ajuntament de Barcelona.
Es tracta d'un espai multi idioma i de fàcil accés, on els usuaris poden trobar una relació de conjunt de dades (catàlegs dataset) que l'Ajuntament de Barcelona posa a la seva disposició de forma reutilitzable.
La informació està classificada en 5 grans temes (administració, població, territori, economia i empresa i ciutat i serveis), amb els seus corresponents subtemes permetent un filtratge.
Des d'inicis de juliol de 2017, disposa del apartat “reutilitzadors”, un espai de comunitat dirigit a, d'una banda, desenvolupadors per facilitar la tasca d'aquest col·lectiu més tècnic en l'ús de les dades, i per l'altre “visualitzacions i aplicacions”, un apartat que dona visibilitat als projectes que es realitzen amb dades del Portal.

Barcelona ja disposa d'experiència i ha començat el camí indicat per el Pla de Transformació Digital, superant els beneficis esperats. Ha arribat, doncs, el moment de *reforçar-la i formalitzar-la*.
////
En este proceso de descubrimiento se va generando un conjunto de documentos que establecen de forma clara los principios, los estándares y los principales procesos de la digitalización abierta y el desarrollo ágil de servicios:

* Estándar de servicios digitales (véase el anexo 12.1).

* Código de prácticas tecnológicas (véase el anexo 12.2).

* Guía y plan de acción de _software_ libre y de código abierto (véase el anexo 12.5).

* •	Guía para la compra pública de TIC: Manual de adquisición de tecnología con cláusulas éticas y abiertas (véase el anexo 12.7).

* Directiva de datos (véase el anexo 12.8).

* Metodologías ágiles en el Ayuntamiento de Barcelona (véase el anexo 12.3).

* Glosario de términos utilizados (véase el anexo 12.10).

Las guías, que acompañan la presente me-dida de gobierno como anexos, se publica-rán como un corpus coherente de trabajo y se irán mejorando a lo largo del proceso de transformación ágil en este mandato.
////
Aquests documents que acompanyen la present mesura de govern com annexos, seran publicades com un corpus coherent de treball i s'aniran millorant en al llarg del procés de transformació àgil en aquest mandat.

Com s'ha indicat anteriorment, les directius sobre dades es desenvoluparà a través d'una futura mesura específica sobre l'ús de dades a l'Ajuntament, donant-li la importància que mereix.
////
