= Proyectos emblemáticos en las líneas de actuación
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

La introducción de los cambios que se derivan del desarrollo de este Programa de digitalización abierta y desarrollo de servicios ágiles se efectúa de forma gradual en un conjunto de proyectos (que se han anunciado en el apartado anterior) que, por este motivo, denominamos _proyectos emblemáticos_.

Estos proyectos serán pioneros en la aplicación de las nuevas prácticas, ya se trate de metodologías de desarrollo ágiles, ya sea en el uso de soluciones basadas en _software_ abierto, la aplicación de estándares abiertos o la implementación de las recomendaciones derivadas de la nueva estrategia de datos.

Así pues, en esta sección presentamos todos los proyectos emblemáticos de este programa de digitalización, y hacemos una breve descripción de cada uno de ellos:

. *Cuadro de mandos para la gerencia municipal.*
Además del desarrollo de un cuadro de mandos para el equipo de gobierno, se desarrollará una aplicación libre y abierta para la ciudadanía que reflejará los indicadores estratégicos de manera sintetizada y aportará datos de los servicios del Ayuntamiento con indicadores de gestión de sus proyectos, el grado de cumplimiento de los compromisos del gobierno, la valoración de la ciudadanía, etcétera.
Este servicio representa un paso importante hacia la transparencia en la gestión municipal y el escrutinio público.

. *Portal de Atención Ciudadana.*
Se renovará el portal de trámites para la ciudadanía y para empresas en Barcelona con el objetivo de simplificar su acceso y utilización y reducir la documentación requerida, cumpliendo con las normas del procedimiento administrativo.
Los ciudadanos percibirán una clara mejora en la usabilidad de los servicios digitales del portal y una simplificación en la tramitación.

. *Servicios municipales en el móvil.* Reducción del número de aplicaciones web.
Se trata de simplificar el uso del portal para ganar en usabilidad.
Se eliminarán las aplicaciones obsoletas, se unificarán aplicaciones, se introducirán nuevas herramientas de código abierto y se incrementará el uso de los datos abiertos.
Se desarrollará un conjunto de nuevas aplicaciones web adaptativas que se pondrán a disposición de la ciudadanía.

. *Decidim Barcelona.*
Desarrollo de la fase 3 de la plataforma de participación ciudadana que incluye funciones de multiconsulta.
Mejorará los servicios de participación que desde el Ayuntamiento se han puesto a disposición de la ciudadanía.

. *Sistema de información de derechos sociales.*
Parte del nuevo sistema de información de la Gerencia de Derechos Sociales se desarrollará con las nuevas metodologías.
De esta forma, se acelerará el desarrollo de los nuevos servicios digitales y la eficiencia de los servicios públicos asociados.

. *ASIA.*
Nueva agenda de acontecimientos y equipamientos de la ciudad.
Este es uno de los servicios digitales más utilizados actualmente por la ciudadanía.
Se mejorará su rendimiento y usabilidad.

. *Sistema de información del Instituto Barcelona Deportes.* Una parte de las aplicaciones que conforman el nuevo sistema de información del Instituto Barcelona Deportes se desarrollará siguiendo las nuevas metodologías ágiles.
La ciudadanía percibirá una mejora en los servicios prestados por este instituto.

. *E-administración.*
Conjunto de aplicaciones y servicios digitales para adaptar la tramitación administrativa al nuevo marco legal.
Una parte de estas aplicaciones se construirá ya con la nueva metodología de desarrollo ágil.
La simplificación de las tramitaciones municipales será el beneficio más tangible para la ciudadanía, que apreciará la reducción de la burocracia y la mejora de los tiempos de respuesta.

. *Migración del correo corporativo a open.*
Se sustituirán los servidores de correo _Exchange_ por una alternativa de código abierto.
Se mantendrá Outlook en local (20 % de los usuarios).
La mejora del servicio impacta en toda la organización municipal.

. *Nueva estación de trabajo Windows (10). Stack de software libre.*
En paralelo a la estación de trabajo 100 % _software_ libre, se creará una basada en Windows con aplicaciones realizadas en _software_ libre.

. *Adopción de herramientas para el desarrollo de aplicaciones basadas en tecnologías abiertas.*
Se pretende implementar un marco que permita desarrollar aplicaciones en código abierto y utilizar herramientas de gestión de los desarrollos basados en tecnologías abiertas.

. *Escritorio abierto.*
Se irá migrando progresivamente las estaciones de trabajo que actualmente tienen instalados aplicaciones y sistemas operativos privativos hacia productos con códigos abiertos.
Hay que valorar que actualmente el Ayuntamiento ya está utilizando aplicaciones de código abierto, como el portal de Open Data, la plataforma de internet de las cosas Sentilo BCN, el banco de imágenes (BIMA) o 12. la plataforma de participación Decidim Barcelona.

. *Identificador Mobile-ID y e-ID.*
Actualmente, hay 18.000 usuarios del identificador móvil con más de 2.000 sesiones de trabajo semanales.
Se actualizará el servicio y se incorporarán nuevos mecanismos de autenticación.
El primer beneficiario de este servicio es la ciudadanía, que dispondrá de una herramienta que le facilitará el uso de los diferentes servicios digitales que ofrece el Ayuntamiento.

. *Servicios desarrollados en código abierto.*
Diversas aplicaciones de las utilizadas por el Ayuntamiento se desarrollarán interna y externamente en código libre y abierto.

. *Servicios City OS.*
Es una plataforma de analítica avanzada de datos con una visión unificada de información de la ciudad, basada en productos open source y que se ofrecerá a la comunidad para detectar problemas, acortar los tiempos de respuesta y mejorar los servicios públicos.
Las diferentes gerencias y direcciones de servicio podrán utilizar esta plataforma de datos para realizar un análisis de la información más detallado y dictar mejores políticas públicas.

. *Cuadro de mandos de ecología.*
Se desarrollará un cuadro de mandos que integre los ámbitos de medio ambiente, urbanismo, infraestructuras, movilidad y servicios urbanos, que aportará una mejor toma de decisiones.

. *Observatorio de la Vivienda de Barcelona.*
Se creará un repositorio de _big data_ especializado en vivienda que permitirá analizar los datos y establecer políticas públicas para combatir los problemas actuales en la vivienda.

. *DCODE.*
Es un proyecto piloto europeo que se desarrolla en Barcelona y Ámsterdam para gestionar la soberanía de los datos para la economía compartida.
Las soluciones técnicas que desarrolla este proyecto servirán para ofrecer servicios mejores y más seguros a la ciudadanía, y a la vez garantizar mejor la propiedad y el control de sus datos.

. *Digital Marketplace.*
Creación de mercado digital para facilitar el acceso de las pequeñas empresas a la contratación pública.

////
. *IRIS.*
Desenvolupament de la nova versió del servei multicanal d'Incidències, Reclamacions i Suggeriments que gestiona les peticions de servei, avisos, incidències i reclamacions dels ciutadans des de l'any 2003.
Aquesta nova versió es desenvoluparà íntegrament en programari de codi obert i es cedirà a la comunitat.

Calendari d'execució dels projectes exemplars relacionats amb l'aplicació de les metodologies àgils i l'ús de programari i estàndards oberts (Figura 5):
////

image::open-digit-p33-schedule-{lang}.svg[_FIGURA 5: Calendari d'execució_]
