= Resumen Ejecutivo
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

En setiembre del 2016, el Ayuntamiento de Barcelona emprendió un importante proceso de transformación digital al anunciar que los servicios públicos deben proveerse ya desde el inicio mediante canales digitales, siguiendo una nueva directriz basada en la orientación a la ciudadanía y el uso de estándares abiertos y software abierto, y de acuerdo con una estrategia de datos ética que da prioridad a la privacidad, a la transparencia y a los derechos digitales.

La decisión del Gobierno de la ciudad está basada en el plan “Barcelona, ciudad digital” (PBCD), aprobado en medida de gobierno el pasado mes de octubre del 2016 y en la nueva Ley española 39/2015 del procedimiento administrativo común de las administraciones públicas.
Esta establece que en el año 2020 en el Estado español los canales digitales tienen que ser prioritarios a la hora de proveer los servicios públicos.
El PBCD establece como uno de sus objetivos prioritarios la mejora radical de los servicios púbicos digitales con la finalidad de proveer a la ciudadanía servicios 24x7 de más calidad y más ajustados a sus necesidades.

El Instituto Municipal de Informática (IMI) es el instrumento para llevar a cabo esta transformación.
El Ayuntamiento de Barcelona creó el pasado año 2016 un comité de transformación digital y, en paralelo, el IMI creó el grupo de impulso de la transformación digital, donde se encuentran profesionales de los diferentes ámbitos tecnológicos.
Ambos instrumentos han sido creados para impulsar y gobernar este importante proceso.

Programa para la digitalización abierta: software libre y desarrollo ágil de servicios, creado por el comisionado y el IMI en octubre del 2016 tras el lanzamiento del Plan digital de transformación, es el impulsor de la innovación y la excelencia técnica enfocado a la entrega de resultados.
Este programa promueve, además, una cultura de la innovación, la transparencia y el aprendizaje continuo en todo el Ayuntamiento, en el que destaca lo siguiente:

* La promoción del desarrollo y la entrega de servicios digitales ágiles, abiertos y éticos.

* La promoción del desarrollo de habilidades y capacidades internas en diseño centrado en el usuario y metodologías ágiles con el fin de recuperar el control de los servicios digitales.

* La apertura de la contratación pública, haciéndola más transparente, sencilla y objetiva, y reduciendo la burocracia.
La innovación en los procesos de contratación permitirá también diversificar los proveedores de tecnología.

* La creación, a través de una plataforma de mercado digital, de un grupo diversificado de proveedores locales expertos.

* La promoción del uso de metodologías ágiles para los servicios digitales, internamente y en las relaciones con proveedores.

* La revisión de los procedimientos de contratación de activos y servicios tecnológicos para reforzar la soberanía tecnológica y de los datos.

* El establecimiento del uso del software libre y de código abierto para los sistemas municipales, excepto circunstancias excepcionales y justificadas.

* La fijación de prácticas tecnológicas basadas en arquitecturas y estándares abiertos.

Esta medida de gobierno proporciona una visión global del programa de transformación y de los cambios incrementales propuestos; expone la estructura de gobernanza de la transformación; muestra su orientación eminentemente práctica basada en el establecimiento de medidas claras y entregas concretas, y proporciona una hoja de ruta compartida.

La medida nos aportará economía de recursos y más eficacia gracias a la implementación de procesos ágiles, al mismo tiempo que acercaremos y facilitaremos a la población herramientas para interactuar con la Administración de manera más eficaz.
Con la gestión abierta de los datos y el uso de herramientas de software libre garantizaremos el acceso universal y la mejora de la transparencia y estaremos sentando las bases para nuevas iniciativas basadas en el aprovechamiento de los datos y la creación de una red de expertos en código abierto que aportará fortaleza e independencia a la Administración.

La medida se centra en la entrega de servicios digitales ágiles, el proceso para alcanzar la soberanía tecnológica y la migración a _software_ libre y estándares de código abierto.

En los anexos a esta medida de gobierno se encuentran documentos que definen los primeros estándares y ofrecen directrices para los temas clave del programa.

Estos documentos son los siguientes:

* El estándar de servicios digitales.

* El código de prácticas tecnológicas.

* Las metodologías Agile en el Ayuntamiento de Barcelona.

* Guía de soberanía tecnológica.

* Detalles del Plan de migración a código abierto.

* Guía de compra pública de tecnología.

El uso responsable y ético de datos es un elemento esencial en el Plan de transformación digital del Ayuntamiento (PTDA), en especial la estrategia de datos abiertos y el _data commons_, los proyectos data driven y la interoperabilidad basada en formatos de datos abiertos.
Las correspondientes directrices y su implementación se desarrollarán en una nueva medida de gobierno sobre la estrategia del uso responsable y ético de datos en el Ayuntamiento de Barcelona, en la que se concretarán los detalles técnicos, los procesos y las responsabilidades.

En esta medida de gobierno también se explica cómo se aplicarán las metodologías de desarrollo ágil en el Ayuntamiento de Barcelona, transformando los equipos de producto verticales en grupos de trabajo ágiles orientados al servicio a través de proyectos emblemáticos.
Por ello, el IMI está poniendo en marcha una oficina técnica ágil y un equipo de proyectos ágiles.

Desde una perspectiva estrictamente tecnológica, el objetivo es la creación de un ecosistema y de una infraestructura pública y abierta de aplicaciones y servicios interoperables y reutilizables.
Por eso, hay que cambiar la forma en que la Administración pública opera mediante el uso de estándares abiertos y _software libre_ y de código abierto, implementando interfaces de programación de aplicaciones (API, por sus siglas en inglés) abiertas, públicas y bien documentadas que proporcionen el acceso a los datos abiertos de la Administración para permitir que el sector de las tecnologías de la información y de la comunicación (TIC) e incluso otras administraciones puedan colaborar con el Ayuntamiento para entregar aplicaciones y servicios digitales ágiles, abiertos y éticos.

Los servicios que primero se beneficiarán de estos cambios son el nuevo portal de atención ciudadana, los servicios en el móvil para la ciudadanía, la nueva agenda de actos y equipamientos de la ciudad, el cuadro de mandos sobre la ciudad abierto a la ciudadanía, el portal para los proveedores de tecnología y el nuevo servicio de identidad digital en el móvil.

Con la formación de los nuevos equipos ágiles, comprenderemos las capacidades que necesitamos y nos permitirá desarrollar un plan de contratación y un programa de creación de competencias internas para impulsar la transformación.
Paralelamente, el Ayuntamiento complementará las competencias internas con habilidades y servicios provistos por las empresas más innovadoras del sector, mediante una contratación innovadora y la creación de una plataforma digital de contratación.

*La transformación digital y la innovación no son el destino o punto de llegada, sino un viaje, un proceso que nunca se acaba* y en el que las iteraciones se van sucediendo una tras otra hasta alcanzar el resultado deseado.
Los productos o servicios digitales y sus interfaces evolucionan, como un organismo vivo, de acuerdo con las necesidades de los ciudadanos y el cambio tecnológico.

El propio Programa de transformación ágil evoluciona continuamente y nuestra ambición es seguir adelante y hacer mucho más de lo que esta medida de gobierno expone, pues esta establece solo las bases de un proceso de mejora continua.
