= Temas y objetivos
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

Para conseguir los objetivos del Programa de digitalización abierta y desarrollo ágil de servicios habrá que trabajar para entregar servicios digitales ágiles y centrados en el usuario, mediante tres ejes principales de acción:

* Fortalecer la soberanía tecnológica, a través de la adopción de _software_ libre y la contratación pública abierta.

* Adoptar las metodologías ágiles, introduciendo un marco de trabajo ágil.

* Mejorar el *gobierno de datos*, mediante una nueva estrategia de datos.

Todo ello se hará mediante un conjunto de actuaciones en cada una de las que conforman el programa (figura 2).

image:open-digit-p20-areas-{lang}.svg[_FIGURA 2: Àrees d'actuació_]

== Servicios digitales ágiles y centrados en el usuario

Hay que cambiar la forma de diseñar y construir los nuevos servicios públicos pensándolos ya como digitales desde el principio, lo que en el mundo anglosajón se denomina _digital first_ (primero en digital).
Hay que diseñarlos poniendo a la ciudadanía en el centro y construyéndolos de forma ágil y gradual para reducir los tiempos de espera para la puesta en marcha.
Es necesario que los trabajadores municipales responsables del servicio, así como la ciudadanía, participen activamente en el diseño, la construcción y el mantenimiento de estos servicios.
Este proceso de cambio, inspirado en los ejemplos de las administraciones anglosajonas, proporcionará nuevos servicios públicos más ajustados a las necesidades reales de la ciudadanía, reduciendo el tiempo de desarrollo.

Los servicios digitales ágiles son el punto de partida para alcanzar los objetivos de este programa de digitalización.
Estos permiten a los ciudadanos, a empresas y a organizaciones relacionarse con el Gobierno de la ciudad de forma más fácil, rápida y económica, pues serán servicios sencillos, rápidos, interactivos y disponibles en todas partes y siempre, servicios que habrán sido diseñados para satisfacer las necesidades de la ciudadanía y de los trabajadores y trabajadoras municipales.
Se desarrollarán servicios pensados en digital desde su inicio y fácilmente adaptables a las nuevas necesidades.

== Metodologías ágiles

Las metodologías ágiles aportarán las herramientas necesarias para diseñar, construir y prestar de manera flexible y eficiente los servicios digitales a la ciudadanía y a los trabajadores y trabajadoras municipales

Para la introducción de un marco de trabajo ágil se necesitará lo siguiente:

* La creación de equipos multidisciplinarios.

* La visión global de todo el ciclo de vida del servicio.

* La introducción progresiva de metodologías ágiles.

* La implicación de toda la organización.

* La realización de proyectos piloto.

* La mejora continua a partir de las aportaciones de todas las partes.

A partir de las líneas de actuación identificadas, detalladas en el apartado 7, se conseguirán los siguientes objetivos:

* Centrarse más en el usuario final empoderándolo para la toma de decisiones.

* Acortar el tiempo de desarrollo y mejorar a la vez la calidad técnica.

* Aumentar la frecuencia de mejoras e implementar la mejora continua.
Entregar más frecuentemente, de manera fiable, para avanzar el retorno de la inversión, y sistematizar la mejora continua basada en ciclos cortos de inspección y adaptación.

* Poner énfasis en la colaboración y la transparencia.

* Incrementar la orientación al valor manteniendo el control de los desarrollos, siendo más flexibles y entregando más valor al usuario final.

Los proyectos emblemáticos en este tema, con un presupuesto total de 7 millones de euros y un calendario que va desde mediados del segundo trimestre del 2017 hasta el final del segundo trimestre del 2019, son los siguientes:

* Cuadro de mandos para la gerencia municipal.

* Portal de atención ciudadana.

* Servicios municipales en el móvil.

* Decidim.Barcelona.

* Sistema de información de derechos sociales.

* ASIA.

* Sistema de información del Instituto Municipal de Deportes.

* E-administración.

== Soberanía tecnológica y tecnologías abiertas

Barcelona exige su soberanía tecnológica y afronta con decisión la transición a _software_ libre y estándares abiertos para esta finalidad.
Se están estudiando las mejores prácticas en este ámbito y se diseñará un plan de migración y se establecerá un código de buenas prácticas sobre tecnologías abiertas que guíe la transformación interna, promueva la reutilización y compartición de código con terceros y de terceros y el desarrollo y utilización de soluciones de gobierno comunes.
La transición a código abierto y estándares abiertos tiene como objetivo reforzar la soberanía tecnológica.

Los sistemas basados en _software_ libre y estándares abiertos ofrecen múltiples beneficios:

////
* *Transparència*: el codi font pot ser examinat i auditat per qualsevol que tingui els coneixements tècnics suficients, sense necessitat de permís explícit del fabricant o de l'Ajuntament.
Sense aquesta propietat es fa difícil confiar en la neutralitat i seguretat d'una quantitat creixent de processos governamentals i administratius que es troben implementats en forma de software, com els processos de votació.

* *Interoperabilitat*: l'ús de formats i estàndards oberts permet que diferents sistemes, possiblement de diferents fabricants, funcionin conjuntament sense obstacles legals i tècnics.
Això obre possibilitats d'integració entre diferents sistemes, per exemple per reutilitzar dades i millorar processos.
També garanteix que no s'obliga als ciutadans i ciutadanes a utilitzar solucions tecnològiques de proveïdors específics per interactuar amb l'Administració.

* *Sobirania*: la transparència i la interoperabilitat redueixen molt la dependència respecte d'estratègies comercials dels fabricants.
L'usuari, en aquest cas l'Ajuntament, pot decidir amb més llibertat quins sistemes evolucionar, redimensionar o substituir, així com establir polítiques pròpies en quant a seguretat, privacitat, actualitzacions i accés als sistemes.
En el cas de les organitzacions, la sobirania també fomenta el control sobre els processos propis i la generació i conservació de coneixement.
////

* *Flexibilidad.*
Los estándares abiertos fomentan la compatibilidad e interoperabilidad entre fabricantes, lo que posibilita instalaciones donde se integren equipos de diferente procedencia y donde se pueden obtener los beneficios de cada producto.
Además, una primera selección de fabricante no impide cambiar en el futuro por otras opciones en caso de mal servicio, mejoras en la competencia u obsolescencia.

////
* *Sostenibilitat*: la interoperabilitat permet que es puguin substituir aquelles parts dels sistemes que cal renovar sense que les dades no quedin mai inservibles.
Una major sobirania implica també un menor risc d'obsolescència de qualsevol part dels sistemes, inclòs el hardware.
La col·laboració (entre persones i entitats) que promouen les llicències lliures pot ser de gran ajuda a l'hora de fer més estable i durador un sistema.

* *Eficiència*: factors com l'estalvi de costos associats al pagament de llicències, una major competència entre proveïdors, un menor risc d'obsolescència, i la possibilitat de compartir costos amb altres usuaris i entitats, fan que el programari lliure i basat en estàndards oberts sigui la millor opció per garantir l'eficiència que la llei exigeix a l'Administració.
La ingent base de programari combinable existent permet en molts dominis aconseguir solucions molt adaptades a l'usuari final amb un baix ús de recursos.
////

* *Fiabilidad y seguridad.*
Con diversos programadores a la vez analizando el mismo trabajo, los errores se detectan y se corrigen antes, por lo que el producto resultante es más fiable y eficaz que el comercial.

////
* *Innovació*: la transparència, i una afortunada combinació de col·laboració i competència, fan del programari lliure un terreny enormement fèrtil per la innovació tecnològica, social i de processos.
D'aquesta producció de coneixement se'n beneficien directament els productors i els usuaris, i indirectament tota la societat.
////

Los principales puntos en los que se debería trabajar son los siguientes:

* Implementar un plan de migración y de-sarrollo progresivo de _software_ libre.

* Publicar y compartir _software_ y contenidos del Ayuntamiento de Barcelona bajo licencia de _software_ y contenidos libres.

* Cambiar la contratación pública para fomentar la creación, el uso y la reutilización del _software_ libre y de código abierto.

* Exigir el uso de estándares abiertos para las tecnologías, datos y otras informaciones de la ciudad.

* Identificar oportunidades de desarrollo y migración a arquitecturas y sistemas abiertos a corto plazo.

La Guía de soberanía tecnología (véase el anexo 12.4) es el documento de referencia en este tema.


== Estrategia responsable de Datos

Los datos son cada vez más importantes para las ciudades, pues permiten definir mejores políticas públicas para combatir las desigualdades sociales, fomentar el desarrollo y mejorar la calidad de vida de la ciudadanía.
El crecimiento exponencial de los datos y la rápida evolución de la tecnología promueven la aparición de nuevos modelos de servicios y generan cambios de hábitos profundos.
Este escenario requiere adecuar de forma flexible y constante las organizaciones TIC y cómo gestionan los datos que manipulan.

Se abre una nueva etapa donde los datos tienen una considerable relevancia en el entorno municipal y de ciudad y se hace patente la necesidad de definir y lanzar un nuevo modelo de gobierno de los datos municipal que actúe con soberanía y sea transversal a todo el Ayuntamiento.

Eso implica cambios organizativos, de funciones y responsabilidades, y hace necesaria la creación en el Ayuntamiento de la figura del responsable de los datos o _chief data officer_ (CDO).

Los principales aspectos en los que habrá que profundizar en este ámbito son los siguientes:

* Nuevas reglas para el gobierno de los datos.

* Arquitectura abierta de datos.

* De los datos a la información, de la in-formación a los indicadores de ciudad.

* Uso ético y responsable de los datos para la innovación.

* Privacidad y soberanía.

La 'Guía de directiva de datos' (véase el ane-xo 12.6) es el documento de referencia en este tema.

== Transformación de la Compra Pública de TIC

Como eje transversal para fortalecer la consecución de los objetivos y los anteriores temas indicados, se deben cambiar los procesos y las prácticas habituales en la compra de tecnología para adaptarlos a las metodologías ágiles que implantar, a la transición al _software_ libre y estándares abiertos y a la nueva estrategia de datos.

La nueva contratación de tecnología será abierta, transparente y más ágil.
Ampliará el abanico de proveedores que pueden acceder a este, y facilitará la contratación de soluciones en código abierto y de estándares abiertos.
Además, considerará los aspectos de propiedad de los datos y la privacidad, observando el cumplimiento de la regulación legal de protección de datos e incluyendo la evaluación del riesgo ético en el uso de los datos.
Como resultado tendremos nuevos procesos de contratación, guías de adquisición de tecnología.

Se generarán nuevos enfoques, nuevas normas y nuevas herramientas con el fin de conseguir las siguientes ventajas:

* Procesos de compra más fáciles.

* Contratación abierta con procesos más transparentes.

* Guías para la contratación de soluciones y servicios basados en tecnologías abiertas y el desarrollo de metodologías ágiles.

////
* Plataforma de mercat digital per facilitar l'accés a proveïdors petits i locals.
////

La Guía de compra pública de tecnología (véase el anexo 12.7) y la Guía de compra pública innovadora (véase el anexo 12.8) son los documentos de referencia en este tema.

== Capacidad, cultura y gestión del cambio organizativo

La transformación ayuda a los equipos existentes a capacitarse y desarrollarse, convirtiéndolos en equipos internos bien preparados con habilidades y capacidades para tomar la plena propiedad de los servicios digitales de la ciudad, los datos, las decisiones arquitectónicas y de compra.

Estas capacidades y habilidades estarán apoyadas por un conjunto de comportamientos y prácticas (cultura organizativa) y una estructura organizativa que, orientándolos a servicios, facilite la colaboración de los equipos con el apoyo puntual de equipos externos que puedan complementar y enriquecer el conocimiento de los recursos internos y abrir nuevas oportunidades profesionales.

////
A continuació (Figura 3), es mostren els resultats més importants, que ja s'han assolit, en les àrees d'actuació descrites.
////

image::open-digit-p25-guides-{lang}.svg[FIGURA 3: Guies]
